const cityByIata: Record<string, string> = {
  "AAA": "Anaa",
  "AAD": "Adado",
  "AAE": "Annaba",
  "AAK": "Aranuka",
  "AAL": "Aalborg",
  "AAM": "Mala Mala",
  "AAN": "Al Ain",
  "AAP": "Samarinda",
  "AAR": "Aarhus",
  "AAT": "Altay",
  "AAX": "Araxa",
  "AAY": "Al Ghaydah",
  "AAZ": "Quetzaltenango",
  "ABA": "Abakan",
  "ABB": "Asaba",
  "ABD": "Abadan",
  "ABE": "Allentown",
  "ABF": "Abaiang",
  "ABI": "Abilene",
  "ABJ": "Abidjan",
  "ABK": "Kabri Dar",
  "ABL": "Ambler",
  "ABM": "Bamaga",
  "ABQ": "Albuquerque",
  "ABR": "Aberdeen",
  "ABS": "Abu Simbel",
  "ABT": "Al Baha",
  "ABU": "Atambua",
  "ABV": "Abuja",
  "ABX": "Albury",
  "ABY": "Albany",
  "ABZ": "Aberdeen",
  "ACA": "Acapulco",
  "ACC": "Accra",
  "ACD": "Acandi",
  "ACE": "Lanzarote",
  "ACF": "Alaer",
  "ACH": "Altenrhein",
  "ACI": "Alderney",
  "ACK": "Nantucket",
  "ACO": "Ascona",
  "ACP": "Sahand",
  "ACT": "Waco",
  "ACV": "Eureka",
  "ACX": "Xingyi",
  "ACY": "Atlantic City",
  "ACZ": "Zabol",
  "ADB": "Izmir",
  "ADD": "Addis Ababa",
  "ADE": "Aden",
  "ADF": "Adiyaman",
  "ADK": "Adak Island",
  "ADL": "Adelaide",
  "ADQ": "Kodiak",
  "ADU": "Ardabil",
  "ADZ": "San Andres",
  "AEA": "Abemama Atoll",
  "AEH": "Abecher",
  "AEP": "Buenos Aires",
  "AER": "Sochi",
  "AES": "Aalesund",
  "AET": "Allakaket",
  "AEU": "Abu Musa",
  "AEX": "Alexandria",
  "AEY": "Akureyri",
  "AFA": "San Rafael",
  "AFL": "Alta Floresta",
  "AGA": "Agadir",
  "AGB": "Augsburg",
  "AGH": "Angelholm",
  "AGM": "Tasiilaq",
  "AGN": "Angoon",
  "AGP": "Malaga",
  "AGR": "Agra",
  "AGS": "Augusta",
  "AGT": "Ciudad Del Este",
  "AGU": "Aguascalientes",
  "AGX": "Agatti Island",
  "AHB": "Abha",
  "AHE": "Ahe",
  "AHO": "Alghero",
  "AHU": "Al Hoceima",
  "AIA": "Alliance",
  "AIC": "Airok",
  "AIM": "Ailuk Island",
  "AIN": "Wainwright",
  "AIP": "Adampur",
  "AIR": "Aripuana",
  "AIS": "Arorae Island",
  "AIT": "Aitutaki",
  "AJA": "Ajaccio",
  "AJF": "Al Jouf",
  "AJI": "Agri",
  "AJL": "Aizawl",
  "AJN": "Anjouan",
  "AJR": "Arvidsjaur",
  "AJU": "Aracaju",
  "AKA": "Ankang",
  "AKI": "Akiak",
  "AKJ": "Asahikawa",
  "AKK": "Akhiok",
  "AKL": "Auckland",
  "AKN": "King Salmon",
  "AKP": "Anaktuvuk Pass",
  "AKR": "Akure",
  "AKS": "Akui",
  "AKU": "Aksu",
  "AKV": "Akulivik",
  "AKX": "Aqtobe",
  "AKY": "Akyab",
  "ALA": "Almaty",
  "ALB": "Albany",
  "ALC": "Alicante",
  "ALF": "Alta",
  "ALG": "Algiers",
  "ALH": "Albany",
  "ALO": "Waterloo",
  "ALS": "Alamosa",
  "ALW": "Walla Walla",
  "ALZ": "Alitak",
  "AMA": "Amarillo",
  "AMD": "Ahmedabad",
  "AMH": "Arba Mintch",
  "AMM": "Amman",
  "AMQ": "Ambon",
  "AMS": "Amsterdam",
  "ANA": "Mara Lodges",
  "ANC": "Anchorage",
  "ANF": "Antofagasta",
  "ANI": "Aniak",
  "ANR": "Antwerp",
  "ANU": "Antigua",
  "ANV": "Anvik",
  "ANX": "Andenes",
  "AOE": "Dorylaeum",
  "AOG": "Anshan",
  "AOI": "Ancona",
  "AOJ": "Aomori",
  "AOK": "Karpathos",
  "AOO": "Altoona",
  "AOR": "Alor Setar",
  "AOS": "Amook Bay",
  "APF": "Naples",
  "APK": "Apataki",
  "APL": "Nampula",
  "APN": "Alpena",
  "APO": "Apartado",
  "APW": "Apia",
  "AQA": "Araraquara",
  "AQG": "Anqing",
  "AQI": "Qaisumah",
  "AQJ": "Aqaba",
  "AQP": "Arequipa",
  "ARC": "Arctic Village",
  "ARD": "Alor Island",
  "ARH": "Arkhangelsk",
  "ARI": "Arica",
  "ARK": "Arusha",
  "ARM": "Armidale",
  "ARN": "Stockholm",
  "ART": "Watertown",
  "ARU": "Aracatuba",
  "ASB": "Ashgabat",
  "ASD": "Andros Town",
  "ASE": "Aspen",
  "ASF": "Astrakhan",
  "ASJ": "Amami O Shima",
  "ASM": "Asmara",
  "ASO": "Asosa",
  "ASP": "Alice Springs",
  "ASR": "Kayseri",
  "ASU": "Asuncion",
  "ASV": "Amboseli",
  "ASW": "Aswan",
  "ATA": "Anta",
  "ATD": "Atoifi",
  "ATH": "Athens",
  "ATK": "Atqasuk",
  "ATL": "Atlanta",
  "ATM": "Altamira",
  "ATQ": "Amritsar",
  "ATT": "Atmautluak",
  "ATW": "Appleton",
  "ATY": "Watertown",
  "ATZ": "Assiut",
  "AUA": "Aruba",
  "AUC": "Arauca",
  "AUG": "Augusta",
  "AUH": "Abu Dhabi",
  "AUK": "Alakanuk",
  "AUL": "Aur Island",
  "AUQ": "Atuona",
  "AUR": "Aurillac",
  "AUS": "Austin",
  "AUU": "Aurukun Mission",
  "AVL": "Asheville",
  "AVP": "Scranton",
  "AVV": "Melbourne",
  "AWA": "Awasa",
  "AWZ": "Ahwaz",
  "AXA": "Anguilla",
  "AXD": "Alexandroupolis",
  "AXM": "Armenia",
  "AXP": "Spring Point",
  "AXR": "Arutua",
  "AXT": "Akita",
  "AXU": "Axum",
  "AXX": "Angel Fire",
  "AYJ": "Ayodhya",
  "AYP": "Ayacucho",
  "AYQ": "Ayers Rock",
  "AYT": "Antalya",
  "AZA": "Phoenix",
  "AZD": "Yazd",
  "AZH": "Azamgarh",
  "AZO": "Kalamazoo",
  "AZR": "Adrar",
  "AZS": "Samana",
  "BAH": "Muharraq",
  "BAL": "Batman",
  "BAQ": "Barranquilla",
  "BAR": "Qionghai",
  "BAS": "Balalae",
  "BAV": "Baotou",
  "BAX": "Barnaul",
  "BAY": "Baia Mare",
  "BBA": "Balmaceda",
  "BBG": "Butaritari",
  "BBI": "Bhubaneswar",
  "BBK": "Kasane",
  "BBN": "Bario",
  "BBU": "Bucharest",
  "BCD": "Bacolod",
  "BCI": "Barcaldine",
  "BCM": "Bacau",
  "BCN": "Barcelona",
  "BCO": "Jinka",
  "BCT": "Boca Raton",
  "BDA": "Bermuda",
  "BDB": "Bundaberg",
  "BDD": "Badu Island",
  "BDH": "Bandar Lengeh",
  "BDJ": "Banjarmasin",
  "BDL": "Hartford",
  "BDO": "Bandung",
  "BDP": "Bhadrapur",
  "BDQ": "Vadodara",
  "BDS": "Brindisi",
  "BDU": "Bardufoss",
  "BEB": "Benbecula",
  "BEF": "Bluefields",
  "BEG": "Belgrade",
  "BEJ": "Berau",
  "BEK": "Rae Bareli",
  "BEL": "Belem",
  "BEM": "Beni Mellal",
  "BEN": "Benghazi",
  "BER": "Berlin",
  "BES": "Brest",
  "BET": "Bethel",
  "BEU": "Bedourie",
  "BEW": "Beira",
  "BEY": "Beirut",
  "BEZ": "Beru",
  "BFD": "Bradford",
  "BFF": "Scottsbluff",
  "BFI": "Seattle",
  "BFJ": "Bijie",
  "BFL": "Bakersfield",
  "BFM": "Mobile",
  "BFN": "Bloemfontein",
  "BFS": "Belfast",
  "BFV": "Buri Ram",
  "BFX": "Bafoussam",
  "BGA": "Bucaramanga",
  "BGC": "Braganca",
  "BGF": "Bangui",
  "BGG": "Bingol",
  "BGI": "Bridgetown",
  "BGM": "Binghamton",
  "BGN": "Belaya Gora",
  "BGO": "Bergen",
  "BGR": "Bangor",
  "BGS": "Boguchany",
  "BGW": "Baghdad",
  "BGY": "Milan",
  "BHB": "Bar Harbor",
  "BHD": "Belfast",
  "BHE": "Blenheim",
  "BHH": "Bisha",
  "BHI": "Bahia Blanca",
  "BHJ": "Bhuj",
  "BHK": "Bukhara",
  "BHM": "Birmingham",
  "BHO": "Bhopal",
  "BHP": "Bhojpur",
  "BHQ": "Broken Hill",
  "BHR": "Bharatpur",
  "BHU": "Bhavnagar",
  "BHX": "Birmingham",
  "BHY": "Beihai",
  "BIA": "Bastia",
  "BIB": "Baidoa",
  "BID": "Block Island",
  "BIH": "Bishop",
  "BIK": "Biak",
  "BIL": "Billings",
  "BIM": "Bimini",
  "BIO": "Bilbao",
  "BIQ": "Biarritz",
  "BIR": "Biratnagar",
  "BIS": "Bismarck",
  "BJA": "Bejaia",
  "BJB": "Bojnord",
  "BJC": "Broomfield",
  "BJF": "Batsfjord",
  "BJI": "Bemidji",
  "BJL": "Banjul",
  "BJM": "Bujumbura",
  "BJR": "Bahar Dar",
  "BJU": "Bajura",
  "BJV": "Bodrum",
  "BJW": "Bajawa",
  "BJX": "Leon",
  "BJZ": "Badajoz",
  "BKA": "Moscow",
  "BKB": "Bikaner",
  "BKC": "Buckland",
  "BKI": "Kota Kinabalu",
  "BKK": "Bangkok",
  "BKM": "Bakalalan",
  "BKO": "Bamako",
  "BKQ": "Blackall",
  "BKS": "Bengkulu",
  "BKW": "Beckley",
  "BKZ": "Bukoba",
  "BLA": "Barcelona",
  "BLB": "Balboa",
  "BLD": "Las Vegas",
  "BLI": "Bellingham",
  "BLJ": "Batna",
  "BLL": "Billund",
  "BLQ": "Bologna",
  "BLR": "Bangalore",
  "BLV": "Belleville",
  "BLZ": "Blantyre",
  "BMA": "Stockholm",
  "BME": "Broome",
  "BMI": "Bloomington",
  "BMO": "Bhamo",
  "BMU": "Bima",
  "BMV": "Banmethuot",
  "BMW": "Bordj Badji Mokhtar",
  "BNA": "Nashville",
  "BND": "Bandar Abbas",
  "BNE": "Brisbane",
  "BNI": "Benin City",
  "BNK": "Ballina",
  "BNN": "Bronnoysund",
  "BNS": "Barinas",
  "BNX": "Banja Luka",
  "BNY": "Bellona",
  "BOB": "Bora Bora",
  "BOC": "Bocas Del Toro",
  "BOD": "Bordeaux",
  "BOG": "Bogota",
  "BOH": "Bournemouth",
  "BOI": "Boise",
  "BOJ": "Bourgas",
  "BOM": "Mumbai",
  "BON": "Bonaire",
  "BOO": "Bodo",
  "BOS": "Boston",
  "BOY": "Bobo Dioulasso",
  "BPA": "Bethpage",
  "BPE": "Qinhuangdao",
  "BPG": "Barra Do Garcas",
  "BPL": "Bole",
  "BPN": "Balikpapan",
  "BPS": "Porto Seguro",
  "BPT": "Beaumont",
  "BPX": "Bangda",
  "BQB": "Busselton",
  "BQJ": "Batagay",
  "BQK": "St Simons Is",
  "BQL": "Boulia",
  "BQN": "Aguadilla",
  "BQS": "Blagoveshchensk",
  "BQT": "Brest",
  "BQU": "Port Elizabeth",
  "BQW": "Balgo Hills",
  "BRA": "Barreiras",
  "BRB": "Barreirinhas",
  "BRC": "San Carlos Bariloche",
  "BRD": "Brainerd",
  "BRE": "Bremen",
  "BRI": "Bari",
  "BRK": "Bourke",
  "BRL": "Burlington",
  "BRM": "Barquisimeto",
  "BRN": "Berne",
  "BRO": "Brownsville",
  "BRQ": "Brno",
  "BRR": "Barra",
  "BRS": "Bristol",
  "BRU": "Brussels",
  "BRW": "Barrow",
  "BSA": "Bossaso",
  "BSB": "Brasilia",
  "BSC": "Bahia Solano",
  "BSD": "Baoshan",
  "BSG": "Bata",
  "BSK": "Biskra",
  "BSL": "Mulhouse Basel",
  "BSO": "Basco",
  "BSR": "Basra",
  "BTC": "Batticaloa",
  "BTH": "Batam",
  "BTI": "Barter Island",
  "BTJ": "Banda Aceh",
  "BTK": "Bratsk",
  "BTM": "Butte",
  "BTR": "Baton Rouge",
  "BTS": "Bratislava",
  "BTT": "Bettles",
  "BTU": "Bintulu",
  "BTV": "Burlington",
  "BTW": "Batulicin",
  "BUA": "Buka Island",
  "BUB": "Burwell",
  "BUC": "Burketown",
  "BUD": "Budapest",
  "BUF": "Buffalo",
  "BUN": "Buenaventura",
  "BUP": "Bhatinda",
  "BUQ": "Bulawayo",
  "BUR": "Burbank",
  "BUS": "Batumi",
  "BUU": "Muara Bungo",
  "BUW": "Baubau",
  "BUZ": "Bushehr",
  "BVA": "Paris",
  "BVB": "Boa Vista",
  "BVC": "Boa Vista",
  "BVE": "Brive La Gaill",
  "BVG": "Berlevag",
  "BVH": "Vilhena",
  "BVI": "Birdsville",
  "BVS": "Breves",
  "BWA": "Bhairawa",
  "BWI": "Baltimore",
  "BWK": "Bol",
  "BWN": "Bandar Seri Bagawan",
  "BWT": "Burnie",
  "BXG": "Bendigo",
  "BXU": "Butuan",
  "BYK": "Bouake",
  "BYO": "Bonito",
  "BYR": "Laeso Island",
  "BYW": "Blakely Island",
  "BZE": "Belize City",
  "BZG": "Bydgoszcz",
  "BZL": "Barisal",
  "BZN": "Bozeman",
  "BZO": "Bolzano",
  "BZR": "Beziers",
  "BZV": "Brazzaville",
  "CAB": "Cabinda",
  "CAC": "Cascavel",
  "CAE": "Columbia",
  "CAG": "Cagliari",
  "CAH": "Ca Mau",
  "CAI": "Cairo",
  "CAJ": "Canaima",
  "CAK": "Akron",
  "CAL": "Campbelltown",
  "CAN": "Guangzhou",
  "CAP": "Cap Haitien",
  "CAT": "Tires",
  "CAU": "Caruaru",
  "CAW": "Campos",
  "CAY": "Cayenne",
  "CAZ": "Cobar",
  "CBB": "Cochabamba",
  "CBG": "Cambridge",
  "CBH": "Bechar",
  "CBI": "Cape Barren Island TAS",
  "CBL": "Ciudad Bolivar",
  "CBO": "Cotabato",
  "CBQ": "Calabar",
  "CBR": "Canberra",
  "CBT": "Catumbela",
  "CCC": "Cayo Coco",
  "CCF": "Carcassonne",
  "CCJ": "Kozhikode",
  "CCK": "Cocos Islands",
  "CCP": "Concepcion",
  "CCR": "Concord",
  "CCS": "Caracas",
  "CCU": "Kolkata",
  "CCZ": "Chub Cay",
  "CDB": "Cold Bay",
  "CDC": "Cedar City",
  "CDE": "Chengde",
  "CDG": "Paris",
  "CDP": "Kadapa",
  "CDR": "Chadron",
  "CDV": "Cordova",
  "CEB": "Cebu",
  "CEC": "Crescent City",
  "CED": "Ceduna",
  "CEE": "Cherepovets",
  "CEI": "Chiang Rai",
  "CEK": "Chelyabinsk",
  "CEN": "Ciudad Obregon",
  "CEZ": "Cortez",
  "CFB": "Cabo Frio",
  "CFE": "Clermont  Ferrand",
  "CFG": "Cienfuegos",
  "CFK": "Chlef",
  "CFN": "Donegal",
  "CFR": "Caen",
  "CFS": "Coffs Harbour",
  "CFU": "Kerkyra",
  "CGA": "Craig",
  "CGB": "Cuiaba",
  "CGD": "Changde",
  "CGH": "Sao Paulo",
  "CGI": "Cape Girardeau",
  "CGK": "Jakarta",
  "CGM": "Mambajao",
  "CGN": "Cologne",
  "CGO": "Zhengzhou",
  "CGP": "Chittagong",
  "CGQ": "Changchun",
  "CGR": "Campogrande",
  "CGY": "Cagayan",
  "CHA": "Chattanooga",
  "CHC": "Christchurch",
  "CHG": "Chaoyang",
  "CHH": "Chachapoyas",
  "CHO": "Charlottesville",
  "CHQ": "Chania",
  "CHS": "Charleston",
  "CHT": "Chatham Island",
  "CHU": "Chuathbaluk",
  "CHX": "Changuinola",
  "CHY": "Choiseul Bay",
  "CIA": "Rome",
  "CID": "Cedar Rapids",
  "CIF": "Chifeng",
  "CIH": "Changzhi",
  "CIJ": "Cobija",
  "CIK": "Chalkyitsik",
  "CIT": "Shimkent",
  "CIU": "Sault Ste Marie",
  "CIX": "Chiclayo",
  "CIY": "Comiso",
  "CIZ": "Coari",
  "CJA": "Cajamarca",
  "CJB": "Coimbatore",
  "CJC": "Calama",
  "CJJ": "Cheongju",
  "CJM": "Chumphon",
  "CJN": "Pangandaran",
  "CJS": "Ciudad Juarez",
  "CJU": "Jeju City",
  "CJZ": "Cajazeiras",
  "CKB": "Clarksburg",
  "CKD": "Crooked Creek",
  "CKG": "Chongqing",
  "CKH": "Chokurdah",
  "CKS": "Carajas",
  "CKX": "Chicken",
  "CKY": "Conakry",
  "CKZ": "Canakkale",
  "CLD": "San Diego",
  "CLE": "Cleveland",
  "CLJ": "Cluj",
  "CLL": "College Station",
  "CLO": "Cali",
  "CLQ": "Colima",
  "CLT": "Charlotte",
  "CLV": "Caldas Novas",
  "CLY": "Calvi",
  "CMA": "Cunnamulla",
  "CMB": "Colombo",
  "CME": "Ciudad Del Carmen",
  "CMF": "Chambery",
  "CMG": "Corumba",
  "CMH": "Columbus",
  "CMI": "Champaign",
  "CMN": "Casablanca",
  "CMW": "Camaguey",
  "CMX": "Houghton",
  "CNC": "Coconut Island",
  "CND": "Constanta",
  "CNF": "Belo Horizonte",
  "CNJ": "Cloncurry",
  "CNM": "Carlsbad",
  "CNN": "Kannur",
  "CNP": "Neerlerit Inaat",
  "CNQ": "Corrientes",
  "CNS": "Cairns",
  "CNX": "Chiang Mai",
  "CNY": "Moab",
  "COD": "Cody",
  "COG": "Condoto",
  "COH": "Cooch Behar",
  "COK": "Kochi",
  "COL": "Coll Island",
  "COO": "Cotonou",
  "COR": "Cordoba",
  "COS": "Colorado Springs",
  "COU": "Columbia",
  "COV": "Mersin",
  "CPC": "Chapelco",
  "CPD": "Coober Pedy",
  "CPE": "Campeche",
  "CPH": "Copenhagen",
  "CPO": "Copiapo",
  "CPR": "Casper",
  "CPT": "Cape Town",
  "CPV": "Campina Grande",
  "CPX": "Culebra",
  "CQD": "Shahre Kord",
  "CQW": "Wulong",
  "CRA": "Craiova",
  "CRD": "Comodoro Rivadavia",
  "CRI": "Crooked Island",
  "CRK": "Luzon Island",
  "CRL": "Brussels",
  "CRM": "Catarman",
  "CRP": "Corpus Christi",
  "CRU": "Carriacou Island",
  "CRV": "Crotone",
  "CRW": "Charleston",
  "CRZ": "Chardzhev",
  "CSA": "Colonsay Island",
  "CSG": "Columbus",
  "CSH": "Solovetsky",
  "CSK": "Cap Skirring",
  "CSX": "Changsha",
  "CSY": "Cheboksary",
  "CTA": "Catania",
  "CTC": "Catamarca",
  "CTD": "Chitre",
  "CTG": "Cartagena",
  "CTL": "Charleville",
  "CTM": "Chetumal",
  "CTN": "Cooktown",
  "CTS": "Sapporo",
  "CTU": "Chengdu",
  "CUC": "Cucuta",
  "CUE": "Cuenca",
  "CUF": "Cuneo",
  "CUK": "Caye Caulker",
  "CUL": "Culiacan",
  "CUM": "Cumana",
  "CUN": "Cancun",
  "CUQ": "Coen",
  "CUR": "Curacao",
  "CUU": "Chihuahua",
  "CUZ": "Cuzco",
  "CVG": "Cincinnati",
  "CVN": "Clovis",
  "CVQ": "Caernarfonshire",
  "CVU": "Corvo Island",
  "CWA": "Wausau",
  "CWB": "Curitiba",
  "CWK": "Chitrakoot",
  "CWL": "Cardiff",
  "CXB": "Coxs Bazaar",
  "CXH": "Vancouver",
  "CXI": "Christmas Island",
  "CXJ": "Caxias Do Sul",
  "CXR": "Cam Ranh",
  "CXY": "Cat Cays",
  "CYA": "Les Cayes",
  "CYB": "Cayman Brac",
  "CYC": "Caye Chapel",
  "CYF": "Chefornak",
  "CYI": "Chiayi",
  "CYO": "Cayo Largo Del Sur",
  "CYP": "Calbayog",
  "CYS": "Cheyenne",
  "CYX": "Cherskiy",
  "CYZ": "Cauayan",
  "CZH": "Corozal",
  "CZL": "Constantine",
  "CZM": "Cozumel",
  "CZN": "Chisana",
  "CZR": "Chara",
  "CZS": "Cruzeiro Do Sul",
  "CZU": "Corozal",
  "CZX": "Changzhou",
  "DAB": "Daytona Beach",
  "DAC": "Dhaka",
  "DAD": "Da Nang",
  "DAL": "Dallas",
  "DAM": "Damascus",
  "DAR": "Dar Es Salaam",
  "DAT": "Datong",
  "DAU": "Daru",
  "DAV": "David",
  "DAY": "Dayton",
  "DBO": "Dubbo",
  "DBQ": "Dubuque",
  "DBR": "Darbhanga",
  "DBV": "Dubrovnik",
  "DCA": "Washington",
  "DCM": "Castres",
  "DDC": "Dodge City",
  "DDG": "Dandong",
  "DDR": "Rikaze",
  "DEB": "Debrecen",
  "DEC": "Decatur",
  "DED": "Dehra Dun",
  "DEE": "Kunashir Island",
  "DEF": "Dezful",
  "DEL": "Delhi",
  "DEM": "Dembidollo",
  "DEN": "Denver",
  "DFW": "Dallas",
  "DGA": "Dangriga",
  "DGE": "Mudgee",
  "DGH": "Deoghar",
  "DGO": "Durango",
  "DGT": "Dumaguete",
  "DHI": "Dhangarhi",
  "DHM": "Dharamsala",
  "DHN": "Dothan",
  "DHX": "Kediri",
  "DIB": "Dibrugarh",
  "DIE": "Diegosuarez",
  "DIG": "Diqing",
  "DIK": "Dickinson",
  "DIL": "Dili",
  "DIN": "Dien Bien Phu",
  "DIQ": "Divinopolis",
  "DIR": "Dire Dawa",
  "DIU": "Diu In",
  "DIY": "Diyarbai",
  "DJB": "Jambi",
  "DJE": "Djerba",
  "DJG": "Djanet",
  "DJJ": "Jayapura",
  "DKA": "Katsina",
  "DKS": "Dikson",
  "DLA": "Douala",
  "DLC": "Dalian",
  "DLE": "Dole",
  "DLG": "Dillingham",
  "DLH": "Duluth",
  "DLI": "Dalat",
  "DLM": "Dalaman",
  "DLU": "Dali City",
  "DLZ": "Dalanzadgad",
  "DMB": "Taraz",
  "DMD": "Doomadgee",
  "DME": "Moscow",
  "DMK": "Bangkok",
  "DMM": "Dammam",
  "DMU": "Dimapur",
  "DND": "Dundee",
  "DNH": "Dunhuang",
  "DNP": "Dang",
  "DNZ": "Denizli",
  "DOB": "Dobo",
  "DOD": "Dodoma",
  "DOH": "Doha",
  "DOL": "Deauville",
  "DOM": "Dominica",
  "DOP": "Dolpa",
  "DOY": "Dongying",
  "DPL": "Dipolog",
  "DPO": "Devonport",
  "DPS": "Denpasar Bali",
  "DQA": "Daqing",
  "DRB": "Derby",
  "DRG": "Deering",
  "DRJ": "Drietabbetje",
  "DRK": "Drake Bay",
  "DRO": "Durango",
  "DRP": "Daraga",
  "DRS": "Dresden",
  "DRW": "Darwin",
  "DSE": "Dessie",
  "DSM": "Des Moines",
  "DSN": "Dongsheng",
  "DTM": "Dortmund",
  "DTW": "Detroit",
  "DUB": "Dublin",
  "DUD": "Dunedin",
  "DUE": "Dundo",
  "DUJ": "Dubois",
  "DUR": "Durban",
  "DUS": "Dusseldorf",
  "DUT": "Dutch Harbor",
  "DVL": "Devils Lake",
  "DVO": "Davao",
  "DWC": "Dubai",
  "DWD": "Dawadmi",
  "DXB": "Dubai",
  "DXJ": "Biancheng",
  "DYG": "Dayong",
  "DYR": "Anadyr",
  "DYU": "Dushanbe",
  "DZA": "Dzaoudzi",
  "DZH": "Daxian",
  "DZN": "Zhezkazgan",
  "EAM": "Nejran",
  "EAR": "Kearney",
  "EAS": "San Sebastian",
  "EAT": "Wenatchee",
  "EAU": "Eau Claire",
  "EBB": "Entebbe",
  "EBG": "El Bagre",
  "EBH": "Hoevenen",
  "EBJ": "Esbjerg",
  "EBL": "Erbil",
  "EBU": "St Etienne",
  "ECN": "Ercan",
  "ECP": "Panama City",
  "EDA": "Edna Bay",
  "EDI": "Edinburgh",
  "EDL": "Eldoret",
  "EDO": "Edremit",
  "EDR": "Edward River",
  "EEA": "Correia",
  "EEK": "Eek",
  "EFL": "Kefalonia",
  "EGC": "Bergerac",
  "EGE": "Eagle",
  "EGM": "Sege",
  "EGS": "Egilsstadir",
  "EHU": "Ezhou",
  "EIN": "Eindhoven",
  "EIS": "Beef Island",
  "EJA": "Barrancabermeja",
  "EJT": "Mili Atoll",
  "EKO": "Elko",
  "EKS": "Shakhtyorsk",
  "ELC": "Elcho",
  "ELD": "El Dorado",
  "ELG": "El Golea",
  "ELH": "North Eleuthera",
  "ELI": "Elim",
  "ELM": "Elmira",
  "ELP": "El Paso",
  "ELQ": "Gassim",
  "ELS": "East London",
  "ELU": "El Oued",
  "ELV": "Elfin Cove",
  "EMA": "Nottingham Uk",
  "EMD": "Emerald",
  "EMK": "Emmonak",
  "EMN": "Nema",
  "ENA": "Kenai",
  "ENE": "Ende",
  "ENH": "Enshi",
  "ENI": "El Nido",
  "ENU": "Enugu",
  "ENY": "Yanan",
  "EOH": "Medellin",
  "EPR": "Esperance",
  "EPU": "Parnu",
  "EQS": "Esquel",
  "ERC": "Erzincan",
  "ERF": "Erfurt",
  "ERH": "Errachidia",
  "ERI": "Erie",
  "ERL": "Erldunda",
  "ERN": "Eirunepe",
  "ERS": "Windhoek",
  "ERZ": "Erzurum",
  "ESB": "Ankara",
  "ESC": "Escanaba",
  "ESD": "East Sound",
  "ESL": "Elista",
  "ESM": "Esmeraldas",
  "ESU": "Essaouira",
  "ETR": "Etrepagny",
  "ETZ": "Metz Nancy",
  "EUA": "Eua",
  "EUG": "Eugene",
  "EUN": "El Aaiun",
  "EUQ": "Antique",
  "EUX": "St Eustatius",
  "EVE": "Harstad Narvik",
  "EVG": "Sveg",
  "EVN": "Yerevan",
  "EVV": "Evansville",
  "EWB": "New Bedford",
  "EWE": "Ewer",
  "EWN": "New Bern",
  "EWR": "New York",
  "EXT": "Exeter",
  "EYA": "Zeya",
  "EYK": "Beloyarsky",
  "EYP": "El Yopal",
  "EYW": "Key West",
  "EZE": "Buenos Aires",
  "EZS": "Elazig",
  "EZV": "Beryozovo",
  "FAC": "Faaite",
  "FAE": "Faeroe Islands",
  "FAI": "Fairbanks",
  "FAO": "Faro",
  "FAR": "Fargo",
  "FAT": "Fresno",
  "FAV": "Fakarava",
  "FAY": "Fayetteville",
  "FBM": "Lubumbashi",
  "FCA": "Kalispell",
  "FCO": "Rome",
  "FDE": "Forde",
  "FDF": "Ft De France",
  "FDH": "Friedrichshafen",
  "FEG": "Fergana",
  "FEN": "Fernando De Noronha",
  "FEZ": "Fez Ma",
  "FGI": "Apia",
  "FGU": "Fangatau",
  "FHZ": "Fakahina",
  "FIE": "Fair Isle",
  "FIH": "Kinshasa",
  "FIZ": "Fitzroy Crossing",
  "FJR": "Al Fujairah",
  "FKB": "Karlsruhe Baden Baden",
  "FKI": "Kisangani",
  "FKQ": "Fak Fak",
  "FKS": "Fukushima",
  "FLA": "Florencia",
  "FLG": "Grand Canyon",
  "FLL": "Ft Lauderdale",
  "FLN": "Florianopolis",
  "FLO": "Florence",
  "FLR": "Florence",
  "FLS": "Flinder Island",
  "FLW": "Santa Cruz Flores",
  "FMA": "Formosa",
  "FMI": "Kalemie",
  "FMM": "Memmingen",
  "FMN": "Farmington",
  "FMO": "Muenster",
  "FMT": "Faresmathoda",
  "FNA": "Freetown",
  "FNC": "Funchal",
  "FND": "Funadhoo",
  "FNI": "Nimes",
  "FNJ": "Pyongyang",
  "FNT": "Flint",
  "FOA": "Foula",
  "FOC": "Fuzhou",
  "FOD": "Fort Dodge",
  "FOG": "Foggia",
  "FON": "Fortuna",
  "FOR": "Fortaleza",
  "FPO": "Freeport",
  "FRA": "Frankfurt",
  "FRD": "Friday Harbor",
  "FRE": "Fera Island",
  "FRL": "Forli",
  "FRO": "Floro",
  "FRS": "Flores",
  "FRU": "Bishkek",
  "FRW": "Francistown",
  "FSC": "Figari",
  "FSD": "Sioux Falls",
  "FSM": "Ft Smith",
  "FSP": "St Pierre",
  "FSZ": "Shizuoka",
  "FTE": "El Calafate",
  "FTI": "Fitiuta",
  "FTU": "Fort Dauphin",
  "FUE": "Puerto Del Rosario",
  "FUG": "Fuyang",
  "FUJ": "Fukue",
  "FUK": "Fukuoka",
  "FUN": "Funafuti",
  "FUO": "Fuoshan",
  "FUT": "Futuna",
  "FWA": "Ft Wayne",
  "FXE": "Ft Lauderdale",
  "FYN": "Fuyun",
  "FYU": "Ft Yukon",
  "GAJ": "Yamagata",
  "GAL": "Galena",
  "GAM": "Gambell",
  "GAN": "Gan Island",
  "GAQ": "Gao",
  "GAU": "Guwahati",
  "GAX": "Gamba",
  "GAY": "Gaya",
  "GBE": "Gaborone",
  "GBI": "Gulbarga",
  "GBT": "Gorgon",
  "GCC": "Gillette",
  "GCH": "Gachsaran",
  "GCI": "Guernsey",
  "GCK": "Garden City",
  "GCM": "Grand Cayman Island",
  "GCN": "Grand Canyon",
  "GCW": "Peach Springs",
  "GDB": "Gondia",
  "GDE": "Gode",
  "GDL": "Guadalajara",
  "GDN": "Gdansk",
  "GDQ": "Gondar",
  "GDT": "Grand Turk",
  "GDV": "Glendive",
  "GDX": "Magadan",
  "GEA": "Noumea",
  "GEG": "Spokane",
  "GEL": "Santo Angelo",
  "GEM": "Mongomo",
  "GEO": "Georgetown",
  "GES": "General Santos",
  "GET": "Geraldton",
  "GEV": "Gallivare",
  "GFF": "Griffith",
  "GFK": "Grand Forks",
  "GGG": "Longview",
  "GGJ": "Guaira",
  "GGM": "Kakamega",
  "GGR": "Garowe",
  "GGT": "George Town",
  "GGW": "Glasgow",
  "GHA": "Ghardaia",
  "GHB": "Governor S Harbour",
  "GHC": "Great Harbour",
  "GHV": "Brasov",
  "GIB": "Gibraltar",
  "GIC": "Boigu Island",
  "GIG": "Rio De Janeiro",
  "GIL": "Gilgit",
  "GIS": "Gisborne",
  "GIT": "Geita",
  "GIZ": "Gizan",
  "GJA": "Guanaja",
  "GJL": "Jijel",
  "GJT": "Grand Junction",
  "GKA": "Goroka",
  "GLA": "Glasgow",
  "GLF": "Golfito",
  "GLH": "Greenville",
  "GLK": "Galcaio",
  "GLN": "Goulimime",
  "GLT": "Gladstone",
  "GLV": "Golovin",
  "GMA": "Gemena",
  "GMB": "Gambela",
  "GME": "Gomel",
  "GMO": "Gombe",
  "GMP": "Seoul",
  "GMR": "Gambier Island",
  "GMZ": "San Sebastian De La Gomera",
  "GNB": "Grenoble",
  "GND": "Grenada",
  "GNJ": "Gyandzha",
  "GNM": "Guanambi",
  "GNS": "Gunungsitoli",
  "GNU": "Goodnews Bay",
  "GNV": "Gainesville",
  "GNY": "Sanliurfa",
  "GOA": "Genoa",
  "GOB": "Goba",
  "GOH": "Nuuk",
  "GOI": "Goa",
  "GOJ": "Nizhniy Novgorod",
  "GOM": "Goma",
  "GOP": "Gorakhpur",
  "GOQ": "Golmud",
  "GOT": "Gothenburg",
  "GOU": "Garoua",
  "GOV": "Gove",
  "GOX": "Goa",
  "GPA": "Patras",
  "GPB": "Guarapuava",
  "GPI": "Guapi",
  "GPS": "Galapagos Is",
  "GPT": "Gulfport",
  "GRB": "Green Bay",
  "GRI": "Grand Island",
  "GRJ": "George",
  "GRK": "Killeen",
  "GRO": "Gerona",
  "GRQ": "Groningen",
  "GRR": "Grand Rapids",
  "GRU": "Sao Paulo",
  "GRV": "Groznyj",
  "GRW": "Graciosa Island",
  "GRX": "Granada",
  "GRZ": "Graz",
  "GSM": "Gheshm",
  "GSO": "Greensboro",
  "GSP": "Greenville",
  "GST": "Glacier Bay",
  "GSV": "Saratov",
  "GTE": "Grte Eylandt",
  "GTF": "Great Falls",
  "GTO": "Gorontalo",
  "GTR": "Columbus",
  "GUA": "Guatemala City",
  "GUC": "Gunnison",
  "GUM": "Guam",
  "GUO": "Guriel",
  "GUP": "Gallup",
  "GUR": "Alotau",
  "GUW": "Atyrau",
  "GVA": "Geneva",
  "GVN": "Sovetskaya Gavan",
  "GVR": "Governador Valadares",
  "GWD": "Gwadar",
  "GWL": "Gwalior",
  "GWT": "Westerland",
  "GXF": "Seiyun",
  "GXH": "Mildenhall",
  "GYA": "Guayaramerin",
  "GYD": "Baku",
  "GYE": "Guayaquil",
  "GYN": "Goiania",
  "GYS": "Guang Yuan",
  "GZG": "Ganzi",
  "GZO": "Gizo",
  "GZP": "Gazipasa",
  "GZT": "Gaziantep",
  "HAA": "Hasvik",
  "HAC": "Hachijo Jima",
  "HAD": "Halmstad",
  "HAH": "Moroni",
  "HAJ": "Hanover",
  "HAK": "Haikou",
  "HAM": "Hamburg",
  "HAN": "Hanoi",
  "HAQ": "Hanimaadhoo",
  "HAS": "Hail",
  "HAU": "Haugesund",
  "HAV": "Havana",
  "HAY": "Haycock",
  "HBA": "Hobart",
  "HBE": "Alexandria",
  "HBX": "Hubli",
  "HCQ": "Halls Creek",
  "HCR": "Holy Cross",
  "HCZ": "Chenzhou",
  "HDF": "Heringsdorf",
  "HDG": "Handan",
  "HDK": "Kulhudhuffushi",
  "HDN": "Hayden",
  "HDO": "Ghaziabad",
  "HDS": "Hoedspruit",
  "HDY": "Hat Yai",
  "HEA": "Herat",
  "HEH": "Heho",
  "HEK": "Heihe",
  "HEL": "Helsinki",
  "HER": "Heraklion",
  "HET": "Hohhot",
  "HFA": "Haifa",
  "HFE": "Hefei",
  "HFS": "Hagfors",
  "HFT": "Hammerfest",
  "HGA": "Hargeisa",
  "HGD": "Hughenden",
  "HGH": "Hangzhou",
  "HGI": "Itanagar",
  "HGN": "Mae Hongson",
  "HGO": "Korhogo",
  "HGR": "Hagerstown",
  "HGU": "Mt Hagen",
  "HHH": "Hilton Head",
  "HHN": "Frankfurt",
  "HHQ": "Hua Hin",
  "HHR": "Hawthorne",
  "HHZ": "Hikueru",
  "HIA": "Thomasville",
  "HIB": "Hibbing",
  "HID": "Horn Island",
  "HIJ": "Hiroshima",
  "HIN": "Chinju",
  "HIR": "Honiara",
  "HJJ": "Zhi Jiang",
  "HJR": "Khajuraho",
  "HKD": "Hakodate",
  "HKG": "Hong Kong",
  "HKK": "Hokitika",
  "HKN": "Hoskins",
  "HKR": "Mara Lodges",
  "HKT": "Phuket",
  "HLA": "Johannesburg",
  "HLD": "Hailar",
  "HLH": "Ulanhot",
  "HLN": "Helena",
  "HLP": "Jakarta",
  "HLZ": "Hamilton",
  "HMA": "Khanty Mansiysk",
  "HMB": "Sohag",
  "HME": "Hassi Messaoud",
  "HMI": "Hami",
  "HMO": "Hermosillo",
  "HMS": "Muara Teweh",
  "HMV": "Hemavan",
  "HNA": "Morioka",
  "HND": "Tokyo",
  "HNH": "Hoonah",
  "HNL": "Honolulu",
  "HNM": "Hana",
  "HNS": "Haines",
  "HNY": "Hengyang",
  "HOB": "Hobbs",
  "HOF": "Hofuf",
  "HOG": "Holguin",
  "HOI": "Hao Island",
  "HOM": "Homer",
  "HOR": "Horta",
  "HOT": "Hot Springs",
  "HOU": "Houston",
  "HOV": "Orsta Volda",
  "HOX": "Homalin",
  "HPA": "Ha Apai",
  "HPB": "Hooper Bay",
  "HPH": "Haiphong",
  "HPN": "White Plains",
  "HQL": "Tashikuergan",
  "HQQ": "An Yang",
  "HRB": "Harbin",
  "HRE": "Harare",
  "HRF": "Hoarafushi",
  "HRG": "Hurghada",
  "HRH": "Aligarh",
  "HRL": "Harlingen",
  "HRO": "Harrison",
  "HSA": "Turkistan",
  "HSC": "Shaoguan",
  "HSG": "Saga",
  "HSL": "Huslia",
  "HSN": "Zhoushan",
  "HSR": "Hirasar",
  "HSV": "Huntsville",
  "HTA": "Chita",
  "HTG": "Hatanga",
  "HTI": "Hamilton Island",
  "HTN": "Hotan",
  "HTS": "Huntington",
  "HTY": "Antakya",
  "HUH": "Huahine",
  "HUI": "Hu PG",
  "HUN": "Hualien",
  "HUS": "Hughes",
  "HUU": "Huanuco",
  "HUX": "Santa Cruz Huatulco",
  "HUY": "Humberside",
  "HUZ": "Huizhou",
  "HVB": "Hervey Bay",
  "HVD": "Khovd",
  "HVG": "Honningsvag",
  "HVN": "New Haven",
  "HVR": "Havre",
  "HWN": "Hwange National Park",
  "HYA": "Hyannis",
  "HYD": "Hyderabad",
  "HYG": "Hydaburg",
  "HYN": "Huangyan",
  "HYS": "Hays",
  "HZA": "Heze",
  "HZG": "Hanzhong",
  "IAA": "Igarka",
  "IAD": "Washington",
  "IAG": "Niagara Falls",
  "IAH": "Houston",
  "IAL": "Salinas",
  "IAM": "In Amenas",
  "IAN": "Kiana",
  "IAO": "Del Carmin",
  "IAR": "Yaroslavl",
  "IAS": "Iasi",
  "IBA": "Ibadan",
  "IBB": "Isabela Island",
  "IBE": "Ibague",
  "IBR": "Omitami Iba",
  "IBZ": "Ibiza",
  "ICI": "Cicia",
  "ICN": "Seoul",
  "ICT": "Wichita",
  "IDA": "Idaho Falls",
  "IDR": "Indore",
  "IEG": "Zielona",
  "IFJ": "Isafjordur",
  "IFN": "Isfahan",
  "IGA": "Inagua",
  "IGR": "Iguazu",
  "IGU": "Iguassu Falls",
  "IHR": "Iran Shahr",
  "IIL": "Ilaam",
  "IJK": "Izhevsk",
  "IKA": "Teheran",
  "IKI": "Iki Jp",
  "IKS": "Tiksi",
  "IKT": "Irkutsk",
  "ILD": "Alguaire",
  "ILG": "Wilmington",
  "ILI": "Iliamna",
  "ILM": "Wilmington",
  "ILO": "Iloilo",
  "ILP": "Ile Des Pins",
  "ILR": "Ilorin",
  "ILY": "Islay",
  "IMF": "Imphal",
  "IMK": "Simikot",
  "IMP": "Imperatriz",
  "IMT": "Iron Mountain",
  "INB": "Independence",
  "INC": "Yinchuan",
  "IND": "Indianapolis",
  "INF": "In Guezzam",
  "INH": "Inhambane",
  "INI": "Nis RS",
  "INL": "International Falls",
  "INN": "Innsbruck",
  "INU": "Nauru Island",
  "INV": "Inverness",
  "INZ": "In Salah",
  "IOA": "Ioannina",
  "IOM": "Isle Of Man",
  "ION": "Impfondo",
  "IOS": "Ilheus",
  "IPC": "Easter Island",
  "IPH": "Ipoh",
  "IPI": "Ipiales",
  "IPL": "El Centro",
  "IPN": "Ipatinga",
  "IPT": "Williamsport",
  "IQM": "Qiemo",
  "IQN": "Qingyang",
  "IQQ": "Iquique",
  "IQT": "Iquitos",
  "IRA": "Kirakira",
  "IRG": "Lockhart",
  "IRI": "Iringa",
  "IRJ": "La Rioja",
  "IRK": "Kirksville",
  "IRM": "Igrim",
  "ISA": "Mount Isa",
  "ISB": "Islamabad",
  "ISC": "Isles Of Scilly",
  "ISE": "Isparta",
  "ISG": "Ishigaki",
  "ISK": "Nasik",
  "ISP": "Islip",
  "IST": "Istanbul",
  "ISU": "Sulaimaniyah",
  "ITB": "Itaituba",
  "ITH": "Ithaca",
  "ITM": "Osaka",
  "ITO": "Hilo",
  "IUE": "Niue",
  "IVC": "Invercargill",
  "IVL": "Ivalo",
  "IVR": "Inverell",
  "IWA": "Ivanovo",
  "IWD": "Ironwood",
  "IWJ": "Iwami",
  "IXA": "Agartala",
  "IXB": "Bagdogra",
  "IXC": "Chandigarh",
  "IXD": "Allahabad",
  "IXE": "Mangalore",
  "IXG": "Belgaum",
  "IXI": "Lilabari",
  "IXJ": "Jammu",
  "IXK": "Keshod",
  "IXL": "Leh IN",
  "IXM": "Madurai",
  "IXR": "Ranchi",
  "IXS": "Silchar",
  "IXT": "Pasighat",
  "IXU": "Aurangabad",
  "IXW": "Jamshedpur",
  "IXY": "Kandla",
  "IXZ": "Port Blair",
  "IZO": "Izumo",
  "JAC": "Jackson",
  "JAE": "Jaen",
  "JAF": "Jaffna",
  "JAI": "Jaipur",
  "JAN": "Jackson",
  "JAU": "Jauja",
  "JAV": "Ilulissat",
  "JAW": "Araripina",
  "JAX": "Jacksonville",
  "JBK": "Qitai",
  "JBQ": "Higuero",
  "JBR": "Jonesboro",
  "JCH": "Qasigiannguit",
  "JCK": "Julia Creek",
  "JCS": "Crateus",
  "JCU": "Ceuta",
  "JDH": "Jodhpur",
  "JDO": "Juazeiro Do Norte",
  "JDZ": "Jingdezhen",
  "JED": "Jeddah",
  "JEG": "Aasiaat",
  "JER": "Jersey",
  "JFK": "New York",
  "JFR": "Paamiut",
  "JGA": "Jamnagar",
  "JGB": "Jagdalpur",
  "JGN": "Jiayuguan",
  "JGO": "Qeqertarsuaq",
  "JGS": "Ji an",
  "JHB": "Johor Bahru",
  "JHG": "Jinghong",
  "JHM": "Kapalua",
  "JHS": "Sisimiut",
  "JIB": "Djibouti",
  "JIJ": "Jijiga",
  "JIK": "Ikaria Island",
  "JIM": "Jimma",
  "JIO": "Ontario",
  "JIU": "Jiujiang",
  "JJN": "Jinjiang",
  "JJU": "Qaqortoq",
  "JKH": "Chios",
  "JKL": "Kalymnos Island",
  "JKR": "Janakpur",
  "JLN": "Joplin",
  "JLR": "Jabalpur",
  "JMA": "Manhuacu",
  "JMK": "Mykonos",
  "JMS": "Jamestown",
  "JMU": "Jiamusi",
  "JNB": "Johannesburg",
  "JNG": "Jining",
  "JNN": "Nanortalik",
  "JNS": "Narsaq",
  "JNU": "Juneau",
  "JNX": "Naxos",
  "JNZ": "Jinzhou",
  "JOE": "Joensuu",
  "JOG": "Yogjakarta",
  "JOI": "Joinville",
  "JOS": "Jos NG",
  "JPA": "Joao Pessoa",
  "JPE": "Paragominas",
  "JPO": "Patos de Paraiba",
  "JPR": "Ji Parana",
  "JQA": "Qaarsut",
  "JRH": "Jorhat",
  "JRK": "Arsuk",
  "JRO": "Kilimanjaro",
  "JSA": "Jaisalmer",
  "JSB": "Sao Benedito",
  "JSH": "Sitia",
  "JSI": "Skiathos",
  "JSO": "Sodertalje",
  "JSR": "Jessore",
  "JST": "Johnstown",
  "JSU": "Maniitsoq",
  "JSY": "Syros Island",
  "JTC": "Baura-Arealva",
  "JTR": "Thira Island",
  "JTY": "Astypalaia Island",
  "JUB": "Juba",
  "JUJ": "Jujuy",
  "JUL": "Juliaca",
  "JUM": "Jumla",
  "JUV": "Upernavik",
  "JUZ": "Juzhou",
  "JWN": "Zanjan",
  "JXA": "Jixi",
  "JYR": "Jiroft",
  "JYV": "Jyvaskyla",
  "JZH": "Songpan",
  "KAA": "Kazama",
  "KAB": "Kariba Dam",
  "KAD": "Kaduna",
  "KAE": "Kake",
  "KAJ": "Kajaani",
  "KAL": "Kaltag",
  "KAN": "Kano",
  "KAO": "Kuusamo",
  "KAW": "Kawthaung",
  "KAZ": "Au ID",
  "KBC": "Birch Creek",
  "KBH": "Kahama",
  "KBL": "Kabul",
  "KBR": "Kota Bharu",
  "KBT": "Kaben",
  "KBU": "Kotabaru",
  "KBV": "Krabi",
  "KCA": "Kuqa",
  "KCC": "Coffman Cove",
  "KCH": "Kuching",
  "KCK": "Kirensk",
  "KCM": "Kahramanmaras",
  "KCT": "Koggala",
  "KCY": "Krasnoyarsk",
  "KCZ": "Kochi",
  "KDH": "Kandahar",
  "KDI": "Kendari",
  "KDL": "Kardla",
  "KDM": "Kaadedhdhoo",
  "KDO": "Kadhdhoo",
  "KDU": "Skardu",
  "KDV": "Kandavu",
  "KDW": "Kandy",
  "KEA": "Keisah",
  "KEF": "Reykjavik",
  "KEI": "Kepi",
  "KEJ": "Kemerovo",
  "KEM": "Kemi",
  "KEO": "Odienne",
  "KEP": "Nepalganj",
  "KER": "Kerman",
  "KET": "Kengtung",
  "KEU": "Mara Lodges",
  "KEW": "Keewaywin",
  "KFA": "Kiffa",
  "KFS": "Kastamonu",
  "KGA": "Kananga",
  "KGC": "Kingscote",
  "KGD": "Kaliningrad",
  "KGE": "Kagau",
  "KGF": "Karaganda",
  "KGI": "Kalgoorlie",
  "KGL": "Kigali",
  "KGP": "Kogalym",
  "KGS": "Kos Gr",
  "KGT": "Kangding",
  "KGX": "Grayling",
  "KHD": "Khorramabad",
  "KHG": "Kashi",
  "KHH": "Kaohsiung",
  "KHI": "Karachi",
  "KHM": "Khamtis",
  "KHN": "Nanchang",
  "KHS": "Khasab",
  "KHT": "Khost",
  "KHV": "Khabarovsk",
  "KHY": "Khoy",
  "KHZ": "Kauehi",
  "KIE": "Kieta",
  "KIF": "Kingfisher Lake",
  "KIH": "Kish Island",
  "KIJ": "Niigata",
  "KIK": "Kirkuk",
  "KIM": "Kimberley",
  "KIN": "Kingston",
  "KIO": "Kili Island",
  "KIR": "Kerry County",
  "KIS": "Kisumu",
  "KIT": "Kithira",
  "KIX": "Osaka",
  "KJA": "Krasnoyarsk",
  "KJB": "Kurnool",
  "KJI": "Buerjin",
  "KKA": "Koyuk",
  "KKB": "Kitoi Bay",
  "KKC": "Khon Kaen",
  "KKE": "Kerikeri",
  "KKH": "Kongiganak",
  "KKI": "Akiachak",
  "KKJ": "Kita Kyushu",
  "KKN": "Kirkenes",
  "KKR": "Kaukura",
  "KKX": "Kikaiga Shima",
  "KLF": "Kaluga",
  "KLG": "Kalskag",
  "KLH": "Kolhapur",
  "KLN": "Larsen Bay",
  "KLO": "Kalibo",
  "KLR": "Kalmar",
  "KLU": "Klagenfurt",
  "KLW": "Klawock",
  "KLX": "Kalamata",
  "KME": "Kamembe",
  "KMG": "Kunming",
  "KMI": "Miyazaki",
  "KMJ": "Kumamoto",
  "KMK": "Makabana",
  "KMQ": "Komatsu",
  "KMS": "Kumasi",
  "KMU": "Kismayu",
  "KMV": "Kalemyo",
  "KMW": "Kostroma",
  "KMY": "Moser Bay",
  "KND": "Kindu",
  "KNG": "Kaimana",
  "KNH": "Kinmen",
  "KNK": "Kakhonak",
  "KNO": "Kuala Namu",
  "KNS": "King Island",
  "KNU": "Kanpur",
  "KNX": "Kununurra",
  "KNY": "Kinoosao",
  "KOA": "Kona",
  "KOE": "Kupang",
  "KOI": "Kirkwall",
  "KOJ": "Kagoshima",
  "KOK": "Kokkola",
  "KOP": "Nakhon Phanom",
  "KOS": "Sihanoukville",
  "KOT": "Kotlik",
  "KOV": "Kokshetau",
  "KOW": "Ganzhou",
  "KOY": "Olga Bay",
  "KOZ": "Ouzinkie",
  "KPB": "Point Baker",
  "KPN": "Kipnuk",
  "KPO": "Pohang",
  "KPR": "Port Williams",
  "KPY": "Port Bailey",
  "KQT": "Qurghonteppa",
  "KRF": "Kramfors",
  "KRK": "Krakow",
  "KRL": "Korla",
  "KRN": "Kiruna",
  "KRO": "Kurgan",
  "KRP": "Karup",
  "KRS": "Kristiansand",
  "KRV": "Kerio Valley",
  "KRW": "Turkmanbashi",
  "KRY": "Karamay",
  "KSA": "Kosrae",
  "KSC": "Kosice",
  "KSE": "Kasese",
  "KSF": "Cassel",
  "KSH": "Kermanshah",
  "KSJ": "Kasos Island",
  "KSL": "Kassala",
  "KSM": "St Marys",
  "KSN": "Kostanay",
  "KSO": "Kastoria",
  "KSQ": "Karshi",
  "KSU": "Kristiansund",
  "KSY": "Kars",
  "KTA": "Karratha",
  "KTB": "Thorne Bay",
  "KTG": "Ketapang",
  "KTJ": "Mara Lodges",
  "KTL": "Kitale",
  "KTM": "Kathmandu",
  "KTN": "Ketchikan",
  "KTR": "Katherine",
  "KTS": "Brevig Mission",
  "KTT": "Kittila",
  "KTW": "Katowice",
  "KUA": "Kuantan",
  "KUC": "Kuria",
  "KUF": "Samara",
  "KUG": "Kubin Island",
  "KUH": "Kushiro",
  "KUK": "Kasigluk",
  "KUL": "Kuala Lumpur",
  "KUM": "Yakushima",
  "KUN": "Kaunas",
  "KUO": "Kuopio",
  "KUS": "Kulusuk",
  "KUT": "Kutaisi",
  "KUU": "Kulu",
  "KUV": "Kunsan",
  "KUZ": "Kunsan",
  "KVA": "Kavalla",
  "KVG": "Kavieng",
  "KVK": "Kirovsk",
  "KVL": "Kivalina",
  "KVO": "Kraljevo",
  "KVR": "Vero Beach",
  "KVX": "Kirov",
  "KWA": "Kwajalein",
  "KWE": "Guiyang",
  "KWI": "Kuwait",
  "KWJ": "Kwangju",
  "KWK": "Kwigillingok",
  "KWL": "Guilin",
  "KWM": "Kowanyama",
  "KWN": "Quinhagak",
  "KWP": "West Point",
  "KWT": "Kwethluk",
  "KWZ": "Kolwezi",
  "KXA": "Kasaan",
  "KXB": "Kolaka",
  "KXF": "Koro",
  "KXO": "Kisoro",
  "KXU": "Katiu",
  "KYA": "Konya",
  "KYK": "Karluk",
  "KYP": "Kyaukpyu",
  "KYS": "Kayes",
  "KYU": "Koyukuk",
  "KYZ": "Kyzyl",
  "KZB": "Zachar Bay",
  "KZI": "Kozani",
  "KZN": "Kazan",
  "KZO": "Kzyl Orda",
  "KZS": "Kastelorizo",
  "LAD": "Luanda",
  "LAE": "Lae Pg",
  "LAF": "Lafayette",
  "LAH": "Labuha",
  "LAK": "Aklavik",
  "LAL": "Lakeland",
  "LAN": "Lansing",
  "LAO": "Laoag",
  "LAP": "La Paz",
  "LAQ": "Beida",
  "LAR": "Laramie",
  "LAS": "Las Vegas",
  "LAU": "Lamu",
  "LAW": "Lawton",
  "LAX": "Los Angeles",
  "LBA": "Leeds",
  "LBB": "Lubbock",
  "LBC": "Hamburg",
  "LBD": "Khudzhand",
  "LBE": "Latrobe",
  "LBF": "North Platte",
  "LBJ": "Labuan Bajo",
  "LBL": "Liberal",
  "LBP": "Long Banga",
  "LBR": "Labrea",
  "LBS": "Labasa",
  "LBU": "Labuan",
  "LBV": "Libreville",
  "LCA": "Larnaca",
  "LCE": "La Ceiba",
  "LCG": "La Coruna",
  "LCH": "Lake Charles",
  "LCJ": "Lodz",
  "LCK": "Columbus",
  "LCR": "La Chorrera",
  "LCX": "Longyan",
  "LCY": "London",
  "LDB": "Londrina",
  "LDE": "Lourdes",
  "LDG": "Leshukonskoye",
  "LDH": "Lord Howe Island",
  "LDS": "Yichun",
  "LDU": "Lahad Datu",
  "LDY": "Londonderry",
  "LDZ": "Londolozi",
  "LEA": "Learmonth",
  "LEB": "Lebanon",
  "LEC": "Lencois",
  "LED": "Saint Petersburg",
  "LEI": "Almeria",
  "LEJ": "Leipzig",
  "LEN": "Leon",
  "LEQ": "Lands End",
  "LET": "Leticia",
  "LEU": "Seo De Urgel",
  "LEX": "Lexington",
  "LFR": "La Fria",
  "LFT": "Lafayette",
  "LFW": "Lome",
  "LGA": "New York",
  "LGB": "Long Beach",
  "LGG": "Liege",
  "LGI": "Deadmans Cay",
  "LGK": "Langkawi",
  "LGL": "Long Lellang",
  "LGW": "London",
  "LGZ": "Shannan",
  "LHE": "Lahore",
  "LHG": "Lightning Ridge",
  "LHN": "Lishan",
  "LHR": "London",
  "LHW": "Lanzhou",
  "LIF": "Lifou",
  "LIG": "Limoges",
  "LIH": "Lihue",
  "LIK": "Likiep",
  "LIL": "Lille",
  "LIM": "Lima",
  "LIN": "Milan",
  "LIO": "Limon",
  "LIR": "Liberia",
  "LIS": "Lisbon",
  "LIT": "Little Rock",
  "LJG": "Lijiang City",
  "LJU": "Ljubljana",
  "LKA": "Larantuka",
  "LKB": "Lakeba",
  "LKE": "Seattle",
  "LKH": "Long Akah",
  "LKI": "Sinabang",
  "LKL": "Lakselv",
  "LKN": "Leknes",
  "LKO": "Lucknow",
  "LKY": "Lake Manyara",
  "LLA": "Lulea",
  "LLB": "Libo City",
  "LLF": "Ling Ling",
  "LLI": "Lalibela",
  "LLK": "Kiryat Shmona",
  "LLM": "Lomlom",
  "LLU": "Alluitsup Paa",
  "LLW": "Lilongwe",
  "LMA": "Lake Minchumina",
  "LMC": "Lamacarena",
  "LMM": "Los Mochis",
  "LMN": "Limbang",
  "LMP": "Lampedusa",
  "LMV": "Naifaru",
  "LNJ": "Lincang",
  "LNK": "Lincoln",
  "LNO": "Leonora",
  "LNS": "Lancaster",
  "LNV": "Lihir Island",
  "LNY": "Lanai",
  "LNZ": "Linz",
  "LOE": "Loei",
  "LOH": "Loja",
  "LOK": "Lodwar",
  "LOO": "Laghouat",
  "LOS": "Lagos",
  "LPA": "Las Palmas",
  "LPB": "La Paz",
  "LPD": "La Pedrera",
  "LPI": "Linkoping",
  "LPL": "Liverpool",
  "LPP": "Lappeenranta",
  "LPQ": "Louangphrabang",
  "LPS": "Lopez Island",
  "LPT": "Lampang",
  "LPY": "Le Puy",
  "LQM": "Puerto Leguizamo",
  "LRD": "Laredo",
  "LRE": "Longreach",
  "LRH": "La Rochelle",
  "LRM": "La Romana",
  "LRR": "Lar",
  "LRS": "Leros",
  "LRT": "Lorient",
  "LRU": "Las Cruces",
  "LRV": "Los Roques",
  "LSC": "La Serena",
  "LSE": "La Crosse",
  "LSH": "Lashio",
  "LSI": "Shetland Islands Area",
  "LSP": "Las Piedras",
  "LST": "Launceston",
  "LSW": "Lhoksumawe",
  "LTI": "Altai",
  "LTK": "Latakia",
  "LTM": "Lethem",
  "LTN": "London",
  "LTO": "Loreto",
  "LUD": "Luderitz",
  "LUH": "Ludhiana",
  "LUM": "Luxi",
  "LUN": "Lusaka",
  "LUO": "Luena",
  "LUP": "Kalaupapa",
  "LUQ": "San Luis",
  "LUR": "Cape Lisburne",
  "LUV": "Langgur",
  "LUW": "Luwuk",
  "LUX": "Luxembourg",
  "LUZ": "Swidnik",
  "LVI": "Livingstone",
  "LVO": "Laverton",
  "LWB": "Lewisburg",
  "LWE": "Lewoleba",
  "LWK": "Shetland Islands Area",
  "LWS": "Lewiston",
  "LWY": "Lawas",
  "LXA": "Lhasa",
  "LXG": "Luang Namtha",
  "LXR": "Luxor",
  "LXS": "Limnos",
  "LYA": "Luoyang",
  "LYB": "Little Cayman",
  "LYC": "Lycksele",
  "LYG": "Lianyungang",
  "LYH": "Lynchburg",
  "LYI": "Linyi",
  "LYP": "Faisalabad",
  "LYR": "Longyearbyen",
  "LYS": "Lyon",
  "LZG": "Langzhong",
  "LZH": "Liuzhou",
  "LZN": "Nangan",
  "LZO": "Luzhou",
  "LZY": "Nyingchi",
  "MAA": "Chennai",
  "MAB": "Maraba",
  "MAD": "Madrid",
  "MAF": "Midland",
  "MAG": "Madang",
  "MAH": "Menorca",
  "MAJ": "Majuro",
  "MAM": "Matamoros",
  "MAN": "Manchester",
  "MAO": "Manaus",
  "MAQ": "Mae Sot",
  "MAR": "Maracaibo",
  "MAS": "Manus Island",
  "MAU": "Maupiti",
  "MAV": "Maloelap",
  "MAZ": "Mayaguez",
  "MBA": "Mombasa",
  "MBE": "Monbetsu",
  "MBI": "Mbeya",
  "MBJ": "Montego Bay",
  "MBL": "Manistee",
  "MBS": "Saginaw",
  "MBT": "Masbate",
  "MBZ": "Maues",
  "MCE": "Merced",
  "MCG": "Mcgrath",
  "MCI": "Kansas City",
  "MCK": "McCook",
  "MCM": "Monte Carlo",
  "MCN": "Macon",
  "MCO": "Orlando",
  "MCP": "Macapa",
  "MCT": "Muscat",
  "MCV": "McArthur River",
  "MCW": "Mason City",
  "MCX": "Makhachkala",
  "MCY": "Maroochydore",
  "MCZ": "Maceio",
  "MDC": "Manado",
  "MDE": "Medellin",
  "MDG": "Mudanjiang",
  "MDK": "Mbandaka",
  "MDL": "Mandalay",
  "MDQ": "Mar Del Plata",
  "MDR": "Medellin",
  "MDT": "Harrisburg",
  "MDW": "Chicago",
  "MDZ": "Mendoza",
  "MEB": "Melbourne",
  "MEC": "Manta",
  "MED": "Madinah",
  "MEE": "Mare",
  "MEH": "Mehamn",
  "MEI": "Meridian",
  "MEL": "Melbourne",
  "MEM": "Memphis",
  "MEU": "Monte Dourado",
  "MEX": "Mexico City",
  "MFA": "Mafia Island",
  "MFE": "McAllen",
  "MFK": "Matsu",
  "MFM": "Macau",
  "MFR": "Medford",
  "MFU": "Mfuwe",
  "MGA": "Managua",
  "MGB": "Mt Gambier",
  "MGF": "Maringa",
  "MGH": "Margate",
  "MGL": "Dusseldorf",
  "MGM": "Montgomery",
  "MGQ": "Mogadishu",
  "MGT": "Milingimbi",
  "MGW": "Morgantown",
  "MGZ": "Myeik",
  "MHD": "Mashad",
  "MHH": "Marsh Harbour",
  "MHK": "Manhattan",
  "MHM": "Malaita",
  "MHQ": "Mariehamn",
  "MHT": "Manchester",
  "MIA": "Miami",
  "MID": "Merida",
  "MIG": "Mian Yang",
  "MII": "Marilia",
  "MIJ": "Mili Island",
  "MIM": "Merimbula",
  "MIR": "Monastir",
  "MIS": "Misima",
  "MIU": "Maiduguri",
  "MJB": "Mejit Island",
  "MJC": "Man",
  "MJE": "Majkin",
  "MJF": "Mosjoen",
  "MJI": "Maji",
  "MJK": "Monkey Mia",
  "MJM": "Mbuji Mayi",
  "MJN": "Majunga",
  "MJT": "Mytilene",
  "MJU": "Mamuju",
  "MJZ": "Mirnyj",
  "MKE": "Milwaukee",
  "MKG": "Muskegon",
  "MKK": "Hoolehua",
  "MKL": "Jackson",
  "MKM": "Mukah",
  "MKP": "Makemo",
  "MKQ": "Merauke",
  "MKR": "Meekathara",
  "MKW": "Manokwari",
  "MKY": "Mackay",
  "MKZ": "Malacca",
  "MLA": "Malta",
  "MLB": "Melbourne",
  "MLE": "Male",
  "MLG": "Malang",
  "MLH": "Mulhouse Basel",
  "MLI": "Moline",
  "MLL": "Marshall",
  "MLM": "Morelia",
  "MLN": "Melilla",
  "MLO": "Milos",
  "MLU": "Monroe",
  "MLX": "Malatya",
  "MMB": "Memambetsu",
  "MME": "Teesside",
  "MMG": "Mount Magnet",
  "MMH": "Mammoth Lakes",
  "MMJ": "Matsumoto",
  "MMK": "Murmansk",
  "MMO": "Maio",
  "MMP": "Mompos",
  "MMU": "Morristown",
  "MMX": "Malmo",
  "MMY": "Miyako Jima",
  "MNA": "Melangguane",
  "MNC": "Nacala",
  "MNG": "Maningrida",
  "MNI": "Montserrat",
  "MNK": "Maiana",
  "MNL": "Manila",
  "MNS": "Mansa",
  "MNU": "Moulmein",
  "MNX": "Manicore",
  "MNY": "Mono",
  "MOB": "Mobile",
  "MOC": "Montes Claros",
  "MOF": "Maumere",
  "MOG": "Mong Hsat",
  "MOH": "Morowali",
  "MOL": "Molde",
  "MOQ": "Morondava",
  "MOT": "Minot",
  "MOU": "Mountain Village",
  "MOV": "Moranbah",
  "MOZ": "Moorea",
  "MPA": "Mpacha",
  "MPH": "Caticlan",
  "MPL": "Montpellier",
  "MPM": "Maputo",
  "MPN": "Mount Pleasant",
  "MQF": "Magnitogorsk",
  "MQJ": "Balikesir",
  "MQL": "Mildura",
  "MQM": "Mardin",
  "MQN": "Mo I Rana",
  "MQP": "Nelspruit",
  "MQS": "Mustique",
  "MQT": "Marquette",
  "MQX": "Makale",
  "MRA": "Misurata",
  "MRE": "Mara Lodges",
  "MRS": "Marseille",
  "MRU": "Mauritius",
  "MRV": "Mineralnye Vody",
  "MRY": "Monterey",
  "MRZ": "Moree",
  "MSA": "Muskrat Dam",
  "MSH": "Masirah",
  "MSJ": "Misawa",
  "MSL": "Muscle Shoals",
  "MSN": "Madison",
  "MSO": "Missoula",
  "MSP": "Minneapolis",
  "MSQ": "Minsk",
  "MSR": "Mus Tr",
  "MSS": "Massena",
  "MST": "Maastricht",
  "MSU": "Maseru",
  "MSY": "New Orleans",
  "MSZ": "Namibe",
  "MTB": "Montelibano",
  "MTJ": "Montrose",
  "MTK": "Makin Island",
  "MTM": "Metlakatla",
  "MTR": "Monteria",
  "MTT": "Minatitlan",
  "MTY": "Monterrey",
  "MUA": "Munda",
  "MUB": "Maun",
  "MUC": "Munich",
  "MUE": "Kamuela",
  "MUH": "Mersa Matruh",
  "MUN": "Maturin",
  "MUR": "Marudi",
  "MUU": "Mount Union",
  "MUX": "Multan",
  "MVB": "Franceville Mvengue",
  "MVD": "Montevideo",
  "MVF": "Mossoro",
  "MVP": "Mitu",
  "MVR": "Maroua",
  "MVT": "Mataiva",
  "MVY": "Martha S Vineyard",
  "MWA": "Marion",
  "MWX": "Gwangju",
  "MWZ": "Mwanza",
  "MXH": "Moro",
  "MXL": "Mexicali",
  "MXP": "Milan",
  "MXQ": "Mitchell River",
  "MXV": "Moron",
  "MXX": "Mora",
  "MXZ": "Meixian",
  "MYA": "Moruya",
  "MYD": "Malindi",
  "MYG": "Mayaguana",
  "MYI": "Murray Island",
  "MYJ": "Matsuyama",
  "MYP": "Mary",
  "MYQ": "Mysore",
  "MYR": "Myrtle Beach",
  "MYT": "Myitkyina",
  "MYW": "Mtwara",
  "MYY": "Miri",
  "MZA": "Mazamari",
  "MZG": "Makung",
  "MZH": "Merzifon",
  "MZK": "Marakei",
  "MZL": "Manizales",
  "MZR": "Mazar I Sharif",
  "MZT": "Mazatlan",
  "MZV": "Mulu",
  "MZW": "Mechria",
  "NAA": "Narrabri",
  "NAG": "Nagpur",
  "NAH": "Naha",
  "NAJ": "Nakhichevan",
  "NAL": "Nalchik",
  "NAM": "Namlea",
  "NAN": "Nadi",
  "NAO": "Nanchong",
  "NAP": "Naples",
  "NAQ": "Qaanaaq",
  "NAS": "Nassau",
  "NAT": "Natal",
  "NAU": "Napuka Island",
  "NAV": "Nevsehir",
  "NAW": "Narathiwat",
  "NBC": "Naberevnye Chelny",
  "NBE": "Enfidha",
  "NBJ": "Luanda",
  "NBO": "Nairobi",
  "NBS": "Baishan",
  "NBX": "Nabire",
  "NCE": "Nice",
  "NCL": "Newcastle",
  "NCN": "New Chenega",
  "NCU": "Nukus",
  "NDB": "Nouadhibou",
  "NDC": "Nanded",
  "NDE": "Mandera",
  "NDG": "Qiqihar",
  "NDJ": "N Djamena",
  "NDK": "Namdrik",
  "NDR": "Nador",
  "NDU": "Runda",
  "NEK": "Nekemt",
  "NER": "Neryungri",
  "NEU": "Sam Neua",
  "NEV": "Nevis",
  "NGB": "Ningbo",
  "NGE": "N Gaoundere",
  "NGK": "Nogliki",
  "NGO": "Nagoya",
  "NGQ": "Shi Quan He",
  "NGS": "Nagasaki",
  "NHV": "Nuku Hiva",
  "NIB": "Nikolai",
  "NIG": "Nikunau",
  "NIM": "Niamey",
  "NIU": "Fakarava Niau",
  "NJC": "Nizhnevartovsk",
  "NJF": "Al Najaf",
  "NKC": "Nouakchott",
  "NKG": "Nanjing",
  "NKI": "Naukiti",
  "NKM": "Nagoya",
  "NLA": "N Dola",
  "NLD": "Nuevo Laredo",
  "NLF": "Darnley Island",
  "NLK": "Norfolk Island",
  "NLT": "Xinyuan",
  "NLU": "Mexico City",
  "NMA": "Namangan",
  "NME": "Nightmute",
  "NMF": "Maafaru",
  "NNB": "Santa Ana",
  "NNG": "Nanning",
  "NNL": "Nondalton",
  "NNM": "Naryan-Mar",
  "NNT": "Nan Th",
  "NNY": "Nanyang",
  "NOB": "Nosara Beach",
  "NOC": "Knock",
  "NOJ": "Nojabrxsk",
  "NON": "Nonouti",
  "NOS": "Nossi Be",
  "NOU": "Noumea",
  "NOV": "Huambo",
  "NOZ": "Novokuznetsk",
  "NPE": "Napier Hastings",
  "NPL": "New Plymouth",
  "NQN": "Neuquen",
  "NQU": "Nuqui",
  "NQY": "Newquay",
  "NQZ": "Astana",
  "NRA": "Narrandera",
  "NRE": "Namrole",
  "NRN": "Dusseldorf",
  "NRR": "Ceiba",
  "NRT": "Tokyo",
  "NSB": "Bimini",
  "NSH": "Now Shahr",
  "NSI": "Yaounde",
  "NSN": "Nelson",
  "NSR": "Serra da Capivara",
  "NST": "Nakhon Si Tham",
  "NTE": "Nantes",
  "NTG": "Nantong",
  "NTL": "Newcastle",
  "NTN": "Normanton",
  "NTQ": "Wajima",
  "NTX": "Natuna Ranai",
  "NUE": "Nuremberg",
  "NUI": "Nuiqsut",
  "NUK": "Nukutavake",
  "NUL": "Nulato",
  "NUM": "Neom Bay",
  "NUP": "Nunapitchuk",
  "NUX": "Novy Urengoy",
  "NVA": "Neiva",
  "NVI": "Navoi",
  "NVT": "Navegantes",
  "NWI": "Norwich",
  "NYA": "Nyagan",
  "NYI": "Sunyani",
  "NYK": "Nanyuki",
  "NYM": "Nadym",
  "NYO": "Stockholm",
  "NYU": "Nyaung",
  "NZG": "Nizhneangarsk",
  "NZH": "Manzhouli",
  "OAG": "Orange",
  "OAJ": "Jacksonville",
  "OAK": "Oakland",
  "OAL": "Cacoal",
  "OAX": "Oaxaca",
  "OBN": "Oban",
  "OBO": "Obihiro",
  "OBU": "Kobuk",
  "OBY": "Ittoqqortoormiit",
  "OCC": "Coca",
  "OCJ": "Ocho Rios",
  "ODN": "Long Seridan",
  "ODY": "Oudomxay",
  "OEC": "Ocussi",
  "OER": "Ornskoldsvik",
  "OFU": "Ofu",
  "OGD": "Ogden",
  "OGG": "Maui",
  "OGL": "Ogle",
  "OGS": "Ogdensburg",
  "OGX": "Ouargla",
  "OGZ": "Vladikavkaz",
  "OHD": "Ohrid",
  "OHE": "Mohe",
  "OHH": "Okha",
  "OHO": "Okhotsk",
  "OIA": "Ourilandia",
  "OIR": "Okushiri",
  "OIT": "Oita",
  "OKA": "Okinawa",
  "OKC": "Oklahoma City",
  "OKD": "Sapporo",
  "OKE": "Okino Erabu",
  "OKI": "Oki Island",
  "OKJ": "Okayama",
  "OKL": "Oksibil",
  "OKR": "Yorke Island",
  "OLA": "Orland",
  "OLB": "Olbia",
  "OLF": "Wolf Point",
  "OLG": "Mara Lodges",
  "OLH": "Old Harbor",
  "OLP": "Olympic Dam",
  "OLX": "Mara Lodges",
  "OMA": "Omaha",
  "OME": "Nome",
  "OMH": "Urmieh",
  "OMO": "Mostar",
  "OMR": "Oradea",
  "OMS": "Omsk",
  "OND": "Ondangwa",
  "ONG": "Mornington",
  "ONJ": "Odate Noshiro",
  "ONQ": "Zonguldak",
  "ONS": "Onslow",
  "ONT": "Ontario",
  "OOK": "Toksook Bay",
  "OOL": "Gold Coast",
  "OOT": "Onotoa",
  "OPF": "Miami",
  "OPO": "Porto",
  "OPP": "Salinopolis",
  "OPS": "Sinop",
  "ORB": "Orebro Bofors",
  "ORD": "Chicago",
  "ORF": "Norfolk",
  "ORG": "Paramaribo",
  "ORH": "Worcester",
  "ORI": "Port Lions",
  "ORK": "Cork",
  "ORN": "Oran",
  "ORU": "Oruro",
  "ORV": "Noorvik",
  "ORY": "Paris",
  "OSD": "Ostersund",
  "OSI": "Osijek",
  "OSJ": "Mara Lodges",
  "OSL": "Oslo",
  "OSR": "Ostrava",
  "OSS": "Osh",
  "OST": "Ostend",
  "OSW": "Orsk",
  "OSY": "Namsos",
  "OTD": "Contadora",
  "OTH": "North Bend",
  "OTI": "Morotai Island",
  "OTP": "Bucharest",
  "OTS": "Ancortes",
  "OTZ": "Kotzebue",
  "OUA": "Ouagadougou",
  "OUD": "Oujda",
  "OUE": "Ouesso",
  "OUI": "Ouessant",
  "OUL": "Oulu",
  "OUZ": "Zouerate",
  "OVB": "Novosibirsk",
  "OVD": "Asturias",
  "OVS": "Boscobel",
  "OWB": "Owensboro",
  "OXB": "Bissau",
  "OYE": "Oyem",
  "OZC": "Philadelphia",
  "OZZ": "Ourzazate",
  "PAB": "Bilaspur",
  "PAC": "Panama City",
  "PAD": "Paderborn",
  "PAE": "Everett",
  "PAF": "Pakuba",
  "PAG": "Pagadian",
  "PAH": "Paducah",
  "PAP": "Port Au Prince",
  "PAS": "Paros",
  "PAT": "Patna",
  "PBA": "Mitchell River",
  "PBC": "Puebla",
  "PBG": "Plattsburgh",
  "PBH": "Paro",
  "PBI": "West Palm Beach",
  "PBM": "Paramaribo",
  "PBO": "Paraburdoo",
  "PBR": "Puerto Barrios",
  "PBU": "Putao",
  "PBZ": "Plettenberg Bay",
  "PCL": "Pucallpa",
  "PCN": "Picton",
  "PCP": "Principe",
  "PCR": "Puerto Carreno",
  "PDA": "Puerto Inirida",
  "PDB": "Pedro Bay",
  "PDG": "Padang",
  "PDL": "Ponta Delgada",
  "PDP": "Punta Del Este",
  "PDS": "Piedras Negras",
  "PDT": "Pendleton",
  "PDV": "Plovdiv",
  "PDX": "Portland",
  "PEC": "Pelican",
  "PED": "Pardubice",
  "PEE": "Perm",
  "PEG": "Perugia",
  "PEI": "Pereira",
  "PEK": "Beijing",
  "PEM": "Puerto Maldonado",
  "PEN": "Penang",
  "PER": "Perth",
  "PES": "Petrozavodsk",
  "PET": "Pelotas",
  "PEU": "Puerto Lempira",
  "PEW": "Peshawar",
  "PEZ": "Penza",
  "PFB": "Passo Fundo",
  "PFO": "Paphos",
  "PFQ": "Parsabad",
  "PGA": "Page",
  "PGD": "Punta Gorda",
  "PGF": "Perpignan",
  "PGH": "Pantnagar",
  "PGK": "Pangkalpinang",
  "PGM": "Port Graham",
  "PGU": "Ala'Marvdasht",
  "PGV": "Greenville",
  "PGZ": "Ponta Grossa",
  "PHB": "Parnaiba",
  "PHC": "Port Harcourt",
  "PHE": "Port Hedland",
  "PHF": "Newport News",
  "PHL": "Philadelphia",
  "PHO": "Point Hope",
  "PHS": "Phitsanulok",
  "PHX": "Phoenix",
  "PIA": "Peoria",
  "PIB": "Laurel",
  "PIE": "Tampa",
  "PIH": "Pocatello",
  "PIK": "Glasgow",
  "PIN": "Parintins",
  "PIR": "Pierre",
  "PIS": "Poitiers",
  "PIT": "Pittsburgh",
  "PIU": "Piura",
  "PIX": "Pico Island",
  "PIZ": "Point Lay",
  "PJA": "Pajala",
  "PJM": "Puerto Jimenez",
  "PKA": "Napaskiak",
  "PKB": "Parkersburg",
  "PKC": "Petropavlovsk Kamchatskiy",
  "PKE": "Parkes",
  "PKN": "Pangkalanbun",
  "PKP": "Pukapuka",
  "PKR": "Pokhara",
  "PKU": "Pekanbaru",
  "PKV": "Pskov",
  "PKX": "Beijing",
  "PKY": "Palangkaraya",
  "PKZ": "Pakse",
  "PLJ": "Placencia",
  "PLM": "Palembang",
  "PLN": "Pellston",
  "PLO": "Port Lincoln",
  "PLQ": "Palanga",
  "PLS": "Providenciales",
  "PLW": "Palu",
  "PLX": "Semipalatinsk",
  "PLZ": "Port Elizabeth",
  "PMA": "Pemba",
  "PMC": "Puerto Montt",
  "PMF": "Milan",
  "PMG": "Ponta Pora",
  "PMI": "Palma Mallorca",
  "PMK": "Palm Island",
  "PMO": "Palermo",
  "PMR": "Palmerston",
  "PMV": "Porlamar",
  "PMW": "Palmas",
  "PMY": "Puerto Madryn",
  "PNA": "Pamplona",
  "PND": "Punta Gorda",
  "PNH": "Phnom Penh",
  "PNI": "Pohnpei",
  "PNK": "Pontianak",
  "PNL": "Pantelleria",
  "PNP": "Popondetta",
  "PNQ": "Pune",
  "PNR": "Pointe Noire",
  "PNS": "Pensacola",
  "PNT": "Puerto Natales",
  "PNY": "Puducherry",
  "PNZ": "Petrolina",
  "POA": "Porto Alegre",
  "POG": "Port Gentil",
  "POJ": "Patos De Minas",
  "POL": "Pemba",
  "POM": "Port Moresby",
  "POP": "Puerto Plata",
  "POR": "Pori",
  "POS": "Port Of Spain",
  "POZ": "Poznan",
  "PPB": "Presidente Prudente",
  "PPG": "Pago Pago",
  "PPK": "Petropavlovsk",
  "PPL": "Phaplu",
  "PPN": "Popayan",
  "PPP": "Proserpine",
  "PPQ": "Paraparaumu",
  "PPS": "Puerto Princesa",
  "PPT": "Papeete",
  "PPV": "Port Protection",
  "PQC": "Phu Quoc",
  "PQI": "Presque Isle",
  "PQQ": "Pt Macquarie",
  "PQS": "Pilot Station",
  "PRA": "Parana",
  "PRC": "Prescott",
  "PRG": "Prague",
  "PRI": "Praslin Island",
  "PRM": "Portimao",
  "PRN": "Pristina",
  "PRS": "Parasi",
  "PSA": "Pisa",
  "PSC": "Pasco",
  "PSE": "Ponce",
  "PSG": "Petersburg",
  "PSM": "Portsmouth",
  "PSO": "Pasto",
  "PSP": "Palm Springs",
  "PSR": "Pescara",
  "PSS": "Posadas",
  "PSU": "Putussibau",
  "PTA": "Port Alsworth",
  "PTG": "Pietersburg",
  "PTO": "Pato Branco",
  "PTP": "Pointe A Pitre",
  "PTQ": "Porto de Moz",
  "PTU": "Platinum",
  "PTX": "Pitalito",
  "PTY": "Panama City",
  "PUB": "Pueblo",
  "PUF": "Pau Fr",
  "PUJ": "Punta Cana",
  "PUK": "Pukarua",
  "PUQ": "Punta Arenas",
  "PUS": "Busan",
  "PUU": "Puerto Asis",
  "PUW": "Pullman",
  "PUY": "Pula",
  "PUZ": "Puerto Cabezas",
  "PVA": "Providencia",
  "PVC": "Provincetown",
  "PVD": "Providence",
  "PVG": "Shanghai",
  "PVH": "Porto Velho",
  "PVK": "Preveza",
  "PVR": "Puerto Vallarta",
  "PVU": "Provo",
  "PWE": "Pevek",
  "PWM": "Portland",
  "PWQ": "Pavlodar",
  "PXM": "Puerto Escondido",
  "PXO": "Porto Santo",
  "PXU": "Pleiku",
  "PYB": "Jeypore",
  "PYH": "Puerto Ayacucho",
  "PYJ": "Polyarnyj",
  "PYT": "Paracatu",
  "PZB": "Pietermaritzburg",
  "PZI": "Panzhihua",
  "PZO": "Puerto Ordaz",
  "PZU": "Port Sudan",
  "QBC": "Bella Coola",
  "QCU": "Akunnaaq",
  "QFI": "Iginniarfik",
  "QGQ": "Attu",
  "QIG": "Iguatu",
  "QJE": "Kitsissuarsuit",
  "QJI": "Ikamiut",
  "QMK": "Niaqornaarsuk",
  "QOW": "Imo",
  "QPW": "Kangaatsiaq",
  "QRO": "Queretaro",
  "QRW": "Warri",
  "QRY": "Ikerasaarsuk",
  "QSF": "Setif",
  "QUP": "Saqqaq",
  "RAB": "Rabaul",
  "RAE": "Arar",
  "RAH": "Rafha",
  "RAI": "Praia",
  "RAK": "Marrakech",
  "RAO": "Ribeirao Preto",
  "RAP": "Rapid City",
  "RAR": "Rarotonga",
  "RAS": "Rasht",
  "RBA": "Rabat",
  "RBB": "Borba",
  "RBQ": "Rurrenabaque",
  "RBR": "Rio Branco",
  "RBV": "Ramata",
  "RBY": "Ruby",
  "RCB": "Richards Bay",
  "RCE": "Roche Harbor",
  "RCH": "Riohacha",
  "RCM": "Richmond",
  "RCU": "Rio Cuarto",
  "RDD": "Redding",
  "RDM": "Redmond",
  "RDN": "Redang",
  "RDO": "Warsaw",
  "RDU": "Raleigh",
  "RDV": "Red Devil",
  "RDZ": "Rodez",
  "REA": "Reao",
  "REC": "Recife",
  "REG": "Reggio Calabria",
  "REL": "Trelew",
  "REN": "Orenburg",
  "RER": "Retalhuleu",
  "RES": "Resistencia",
  "RET": "Rost",
  "REU": "Reus",
  "REX": "Reynosa",
  "REZ": "Resende",
  "RFD": "Chicago",
  "RFP": "Raiatea",
  "RGA": "Rio Grande",
  "RGI": "Rangiroa Island",
  "RGK": "Gorno-Altaisk",
  "RGL": "Rio Gallegos",
  "RGN": "Yangon",
  "RGS": "Burgos",
  "RHD": "Rio Hondo",
  "RHI": "Rhinelander",
  "RHO": "Rhodes",
  "RIA": "Santa Maria",
  "RIB": "Riberalta",
  "RIC": "Richmond",
  "RIL": "Rifle",
  "RIS": "Rishiri",
  "RIW": "Riverton",
  "RIX": "Riga",
  "RIY": "Riyan",
  "RIZ": "Rizhao",
  "RJA": "Rajahmundry",
  "RJB": "Rajbiraj",
  "RJH": "Rajshahi",
  "RJK": "Rijeka",
  "RJL": "Logrono",
  "RKA": "Aratika",
  "RKD": "Rockland",
  "RKE": "Copenhagen",
  "RKS": "Rock Springs",
  "RKT": "Ras Al Khaimah",
  "RKV": "Reykjavik",
  "RLG": "Rostock Laage",
  "RLO": "Santa Rose de Conlara",
  "RMA": "Roma",
  "RMF": "Marsa Alam",
  "RMI": "Rimini",
  "RMO": "Chisinau",
  "RMQ": "Taichung",
  "RMT": "Rimatara",
  "RMZ": "Tobolsk",
  "RNA": "Arona",
  "RNB": "Ronneby",
  "RNI": "Corn Island",
  "RNJ": "Yoronjima",
  "RNL": "Rennell",
  "RNN": "Bornholm",
  "RNO": "Reno",
  "RNS": "Rennes",
  "ROA": "Roanoke",
  "ROB": "Monrovia",
  "ROC": "Rochester",
  "ROI": "Roi Et",
  "ROK": "Rockhampton",
  "RON": "Rondon",
  "ROO": "Rondonopolis",
  "ROP": "Rota",
  "ROR": "Koror",
  "ROS": "Rosario",
  "ROT": "Rotorua",
  "ROW": "Roswell",
  "RPR": "Raipur",
  "RQY": "Shivamogga",
  "RRG": "Rodrigues Island",
  "RRK": "Rourkela",
  "RRR": "Raroia",
  "RRS": "Roros",
  "RSA": "Santa Rosa",
  "RSD": "Rock Sound",
  "RSH": "Russian Mission",
  "RSI": "Rio Sidra",
  "RST": "Rochester",
  "RSU": "Yeosu",
  "RSW": "Fort Myers",
  "RTA": "Rotuma Island",
  "RTB": "Roatan",
  "RTG": "Ruteng",
  "RTI": "Rote Island",
  "RTM": "Rotterdam",
  "RTW": "Saratov",
  "RUA": "Arua",
  "RUH": "Riyadh",
  "RUL": "Maavarulu",
  "RUN": "Reunion Island",
  "RUP": "Rupsi",
  "RUR": "Rurutu",
  "RUT": "Rutland",
  "RVD": "Rio Verde",
  "RVE": "Saravena",
  "RVK": "Roervik",
  "RVN": "Rovaniemi",
  "RVV": "Rairua",
  "RXS": "Roxas City",
  "RZE": "Rzeszow",
  "RZH": "Lancaster",
  "RZR": "Ramsar",
  "RZV": "Rize",
  "SAB": "Saba Island",
  "SAE": "Saattut",
  "SAF": "Santa Fe",
  "SAG": "Shirdi",
  "SAH": "Sanaa",
  "SAI": "San Marino",
  "SAL": "San Salvador",
  "SAN": "San Diego",
  "SAP": "San Pedro Sula",
  "SAQ": "San Andros",
  "SAT": "San Antonio",
  "SAU": "Sawu",
  "SAV": "Savannah",
  "SAW": "Istanbul",
  "SBA": "Santa Barbara",
  "SBD": "San Bernardino",
  "SBH": "St Barthelemy",
  "SBN": "South Bend",
  "SBP": "San Luis Obispo",
  "SBR": "Saibai Island",
  "SBW": "Sibu",
  "SBY": "Salisbury Ocean City",
  "SBZ": "Sibiu",
  "SCC": "Prudhoe Bay Deadhorse",
  "SCE": "State College",
  "SCF": "Phoenix",
  "SCK": "Stockton",
  "SCL": "Santiago",
  "SCM": "Scammon Bay",
  "SCN": "Saarbruecken",
  "SCO": "Aktau",
  "SCQ": "Santiago De Compostela",
  "SCR": "Salen",
  "SCT": "Socotra",
  "SCU": "Santiago",
  "SCV": "Suceava",
  "SCW": "Syktyvkar",
  "SCY": "San Cristobal",
  "SCZ": "Santa Cruz Island",
  "SDD": "Lubango",
  "SDE": "Santiago Del Estero",
  "SDF": "Louisville",
  "SDJ": "Sendai",
  "SDK": "Sandakan",
  "SDL": "Sundsvall",
  "SDN": "Sandane",
  "SDP": "Sand Point",
  "SDQ": "Santo Domingo",
  "SDR": "Santander",
  "SDU": "Rio De Janeiro",
  "SDW": "Sandwip",
  "SDY": "Sidney",
  "SEA": "Seattle",
  "SEB": "Sebha",
  "SEK": "Srednekolymsk",
  "SEN": "Southend",
  "SES": "SELMA",
  "SEU": "Seronera",
  "SEZ": "Mahe Island",
  "SFA": "Sfax",
  "SFB": "Orlando",
  "SFG": "St Martin",
  "SFJ": "Kangerlussuaq",
  "SFL": "Sao Filipe",
  "SFN": "Santa Fe",
  "SFO": "San Francisco",
  "SFT": "Skelleftea",
  "SGC": "Surgut",
  "SGD": "Sonderborg",
  "SGF": "Springfield",
  "SGG": "Sermiligaaq",
  "SGN": "Ho Chi Minh City",
  "SGO": "St George",
  "SGU": "St George",
  "SGX": "Songea",
  "SGY": "Skagway",
  "SHA": "Shanghai",
  "SHB": "Nakashibetsu",
  "SHC": "Shire Indaselassie",
  "SHD": "Staunton",
  "SHE": "Shenyang",
  "SHF": "Shihezi",
  "SHG": "Shungnak",
  "SHH": "Shismaref",
  "SHI": "Shimojishima",
  "SHJ": "Sharjah",
  "SHL": "Shillong",
  "SHM": "Nanki Shirahama",
  "SHO": "Manzini",
  "SHR": "Sheridan",
  "SHS": "Shashi",
  "SHV": "Shreveport",
  "SHW": "Sharurah",
  "SHX": "Shageluk",
  "SID": "Sal Island",
  "SIF": "Simara",
  "SIG": "San Juan",
  "SIN": "Singapore",
  "SIQ": "Singkep",
  "SIR": "Jerusalem",
  "SIS": "Sishen",
  "SIT": "Sitka",
  "SJC": "San Jose",
  "SJD": "San Jose Cabo",
  "SJE": "San Jose Guaviare",
  "SJI": "San Jose",
  "SJJ": "Sarajevo",
  "SJK": "Sao Jose Dos Campos",
  "SJL": "Sao Gabriel",
  "SJO": "San Jose",
  "SJP": "Sao Jose Do Rio Preto",
  "SJT": "San Angelo",
  "SJU": "San Juan",
  "SJW": "Shijiazhuang",
  "SJZ": "Sao Jorge Island",
  "SKB": "St Kitts",
  "SKD": "Samarkand",
  "SKG": "Thessaloniki",
  "SKH": "Surkhet",
  "SKK": "Shaktoolik",
  "SKN": "Stokmarknes",
  "SKO": "Sokoto",
  "SKP": "Skopje",
  "SKT": "Sialkot",
  "SKU": "Skiros",
  "SKX": "Saransk",
  "SKZ": "Sukkur",
  "SLA": "Salta",
  "SLC": "Salt Lake City",
  "SLE": "Salem",
  "SLI": "Solwezi",
  "SLK": "Saranac Lake",
  "SLL": "Salalah",
  "SLM": "Salamanca",
  "SLN": "Salina",
  "SLP": "San Luis Potosi",
  "SLQ": "Sleetmute",
  "SLU": "St Lucia",
  "SLV": "Simla",
  "SLX": "Salt Cay",
  "SLY": "Salehard",
  "SLZ": "Sao Luiz",
  "SMA": "Santa Maria",
  "SMF": "Sacramento",
  "SMI": "Samos",
  "SMK": "St Michael",
  "SML": "Stella Maris",
  "SMQ": "Sampit",
  "SMR": "Santa Marta",
  "SMS": "Saint Marie",
  "SMT": "Sorriso",
  "SMV": "Saint Moritz",
  "SMX": "Santa Maria",
  "SMZ": "Stoelmanseiland",
  "SNA": "Santa Ana",
  "SNE": "Sao Nicolau",
  "SNN": "Shannon",
  "SNO": "Sakon Nakhon",
  "SNP": "St Paul Island",
  "SNR": "St Nazaire",
  "SNU": "Santa Clara",
  "SNW": "Sandoway",
  "SOC": "Solo",
  "SOF": "Sofia",
  "SOG": "Sogndal",
  "SOJ": "Sorkjosen",
  "SON": "Espiritu Santo",
  "SOQ": "Sorong",
  "SOU": "Southampton",
  "SOV": "Seldovia",
  "SOW": "Show Low",
  "SPB": "St Thomas",
  "SPC": "Santa Cruz",
  "SPD": "Saidpur",
  "SPI": "Springfield",
  "SPN": "Saipan",
  "SPP": "Menongue",
  "SPR": "San Pedro",
  "SPS": "Wichita Falls",
  "SPU": "Split",
  "SPX": "Houston",
  "SPY": "San Pedro",
  "SQG": "Sintang",
  "SQJ": "Sanming",
  "SQN": "Sanana",
  "SRE": "Sucre",
  "SRG": "Semarang",
  "SRK": "Siorapaluk",
  "SRP": "Stord",
  "SRQ": "Sarasota",
  "SRV": "Stony River",
  "SRY": "Sary",
  "SSA": "Salvador",
  "SSB": "St Croix",
  "SSG": "Malabo",
  "SSH": "Sharm El Sheik",
  "SSJ": "Sandnessjoen",
  "STB": "Santa Barbara",
  "STC": "Saint Cloud",
  "STD": "Santo Domingo",
  "STI": "Santiago",
  "STL": "St Louis",
  "STM": "Santarem",
  "STN": "London",
  "STR": "Stuttgart",
  "STS": "Santa Rosa",
  "STT": "St Thomas",
  "STV": "Surat",
  "STW": "Stavropol",
  "STX": "St Croix",
  "STY": "Salto",
  "SUA": "Alice Springs",
  "SUB": "Surabaya",
  "SUF": "Lamezia Terme",
  "SUG": "Surigao",
  "SUJ": "Satu Mare",
  "SUK": "Batagay-Alyta",
  "SUN": "Sun Valley",
  "SUR": "Summer Beaver",
  "SUV": "Suva",
  "SUX": "Sioux City",
  "SUY": "Suntar",
  "SVA": "Savoonga",
  "SVB": "Sambava",
  "SVC": "Silver City",
  "SVD": "St Vincent",
  "SVG": "Stavanger",
  "SVI": "San Vincent",
  "SVJ": "Svolvaer",
  "SVL": "Savonlinna",
  "SVO": "Moscow",
  "SVP": "Kuito",
  "SVQ": "Sevilla",
  "SVR": "Savissivik",
  "SVU": "Savusavu",
  "SVX": "Ekaterinburg",
  "SVZ": "San Antonio",
  "SWA": "Shantou",
  "SWF": "Newburgh",
  "SWO": "Stillwater",
  "SWQ": "Sumbawa Besar",
  "SWT": "Strezhevoy",
  "SWV": "Evensk",
  "SXB": "Strasbourg",
  "SXK": "Saumlaki",
  "SXM": "St Maarten",
  "SXP": "Sheldon Point",
  "SXR": "Srinagar",
  "SXV": "Salem",
  "SXZ": "Siirt",
  "SYB": "Seal Bay",
  "SYD": "Sydney",
  "SYJ": "Sirjan",
  "SYM": "Simao",
  "SYO": "Shonai",
  "SYR": "Syracuse",
  "SYS": "Saskylakh",
  "SYU": "Sue Island",
  "SYX": "Sanya",
  "SYY": "Stornoway",
  "SYZ": "Shiraz",
  "SZA": "Soyo",
  "SZB": "Kuala Lumpur",
  "SZC": "Santa Cruz",
  "SZE": "Semera",
  "SZF": "Samsun",
  "SZG": "Salzburg",
  "SZH": "Senipah",
  "SZK": "Skukuza",
  "SZX": "Shenzhen",
  "SZY": "Szymany",
  "SZZ": "Szczecin",
  "TAB": "Tobago",
  "TAC": "Tacloban",
  "TAE": "Daegu",
  "TAG": "Tagbilaran",
  "TAK": "Takamatsu",
  "TAL": "Tanana",
  "TAM": "Tampico",
  "TAO": "Qingdao",
  "TAP": "Tapachula",
  "TAS": "Tashkent",
  "TAT": "Poprad Tatry",
  "TAY": "Tartu",
  "TAZ": "Dashoguz",
  "TBB": "Tuy Hoa",
  "TBF": "Tabiteuea",
  "TBG": "Tububil",
  "TBH": "Tablas",
  "TBI": "The Bight",
  "TBN": "Ft Leonard Wood",
  "TBO": "Tabora",
  "TBP": "Tumbes",
  "TBS": "Tbilisi",
  "TBT": "Tabatinga",
  "TBU": "Nuku Alofa",
  "TBW": "Tambov",
  "TBZ": "Tabriz",
  "TCA": "Tennant Creek",
  "TCB": "Treasure Cay",
  "TCD": "Tarapaca",
  "TCG": "Tacheng",
  "TCO": "Tumaco",
  "TCQ": "Tacna",
  "TCR": "Tuticorin",
  "TCT": "Takotna",
  "TCX": "Tabas",
  "TCZ": "Tengchong",
  "TDD": "Trinidad",
  "TDK": "Taldykorgan",
  "TDX": "Trat",
  "TEB": "Teterboro",
  "TEC": "Telemaco Borba",
  "TEE": "Tbessa",
  "TEI": "Tezu",
  "TEK": "Tatitlek",
  "TEN": "Tongren",
  "TEQ": "Tekirdag",
  "TER": "Terceira",
  "TET": "Tete",
  "TEX": "Telluride",
  "TFF": "Tefe",
  "TFL": "Teofilo Otoni",
  "TFN": "Tenerife",
  "TFS": "Tenerife",
  "TFU": "Chengdu",
  "TGC": "Trenton",
  "TGD": "Podgorica",
  "TGG": "Kuala Terengganu",
  "TGI": "Tingo Maria",
  "TGM": "Tirgu Mures",
  "TGO": "Tongliao",
  "TGR": "Touggourt",
  "TGT": "Tanga",
  "TGU": "Tegucigalpa",
  "TGZ": "Tuxtla Gutierrez",
  "THE": "Teresina",
  "THL": "Tachilek",
  "THN": "Trollhattan",
  "THO": "Thorshofn",
  "THQ": "Tianshui",
  "THR": "Teheran",
  "THS": "Sukhothai",
  "THU": "Pituffik",
  "TIA": "Tirana",
  "TID": "Tiaret",
  "TIF": "Taif",
  "TIH": "Tikehau",
  "TIJ": "Tijuana",
  "TIM": "Timika",
  "TIN": "Tindouf",
  "TIR": "Tirupati",
  "TIU": "Timaru",
  "TIV": "Tivat",
  "TIZ": "Tari",
  "TJA": "Tarija",
  "TJH": "Toyooka",
  "TJK": "Tokat",
  "TJM": "Tyumen",
  "TJN": "Takume",
  "TJQ": "Tanjung Pandan",
  "TJU": "Kulob",
  "TKD": "Takoradi",
  "TKE": "Tenakee",
  "TKG": "Bandar Lampung",
  "TKJ": "Tok Ak",
  "TKK": "Truk",
  "TKM": "Tikal",
  "TKN": "Tokunoshima",
  "TKP": "Takapoto",
  "TKQ": "Kigoma",
  "TKS": "Tokushima",
  "TKU": "Turku",
  "TKV": "Tatakoto",
  "TKX": "Takaroa",
  "TLA": "Teller",
  "TLC": "Mexico City",
  "TLE": "Tulear",
  "TLH": "Tallahassee",
  "TLI": "Toli Toli",
  "TLJ": "Tatalina",
  "TLK": "Talakan",
  "TLL": "Tallinn",
  "TLM": "Tlemcen",
  "TLN": "Toulon",
  "TLQ": "Turpan",
  "TLS": "Toulouse",
  "TLT": "Tuluksak",
  "TLU": "Tolu",
  "TLV": "Tel Aviv",
  "TLY": "Plastun",
  "TMC": "Tambolaka",
  "TME": "Tame",
  "TMH": "Tanahmerah",
  "TMI": "Tumling Tar",
  "TMJ": "Termez",
  "TML": "Tamale",
  "TMM": "Tamatave",
  "TMN": "Tamana Island",
  "TMP": "Tampere",
  "TMR": "Tamenghest",
  "TMS": "Sao Tome",
  "TMT": "Trombetas",
  "TMW": "Tamworth",
  "TMX": "Timimoun",
  "TNA": "Jinan",
  "TNC": "Tin City",
  "TNE": "Tanega Shima",
  "TNG": "Tangier",
  "TNH": "Sanyuanpu",
  "TNJ": "Tanjung Pinang",
  "TNK": "Tununak",
  "TNN": "Tainan",
  "TNO": "Tamarindo",
  "TNR": "Antananarivo",
  "TOB": "Tobruk",
  "TOE": "Tozeur",
  "TOF": "Tomsk",
  "TOL": "Toledo",
  "TOM": "Tombouctou",
  "TOS": "Tromso",
  "TOY": "Toyama",
  "TPA": "Tampa",
  "TPE": "Taipei",
  "TPJ": "Taplejung",
  "TPP": "Tarapoto",
  "TPQ": "Tepic",
  "TPS": "Trapani",
  "TQO": "TULUM",
  "TQQ": "Tomia",
  "TQR": "San Domino Island",
  "TRC": "Torreon",
  "TRD": "Trondheim",
  "TRE": "Tiree",
  "TRF": "Oslo",
  "TRG": "Tauranga",
  "TRI": "Bristol",
  "TRK": "Tarakan",
  "TRM": "Thermal",
  "TRN": "Turin",
  "TRR": "Trincomalee",
  "TRS": "Trieste",
  "TRT": "Tremonton",
  "TRU": "Trujillo",
  "TRV": "Thiruvananthapuram",
  "TRW": "Tarawa",
  "TRZ": "Tiruchirappali",
  "TSA": "Taipei",
  "TSF": "Venice",
  "TSJ": "Tsushima",
  "TSM": "Taos",
  "TSN": "Tianjin",
  "TSR": "Timisoara",
  "TST": "Trang",
  "TSU": "Tabiteuea South",
  "TSV": "Townsville",
  "TTA": "Tan Tan",
  "TTE": "Ternate",
  "TTJ": "Tottori",
  "TTN": "Trenton",
  "TTQ": "Tortuquero",
  "TTT": "Taitung",
  "TTU": "Tetuan",
  "TUB": "Tubuai",
  "TUC": "Tucuman",
  "TUF": "Tours",
  "TUG": "Tuguegarao",
  "TUI": "Turaif",
  "TUK": "Turbat",
  "TUL": "Tulsa",
  "TUN": "Tunis",
  "TUO": "Taupo",
  "TUP": "Tupelo",
  "TUR": "Tucurui",
  "TUS": "Tucson",
  "TUU": "Tabuk",
  "TVC": "Traverse City",
  "TVF": "Thief River Falls",
  "TVS": "Tangshan",
  "TVU": "Taveuni",
  "TVY": "Tavoy",
  "TWF": "Twin Falls",
  "TWT": "Tawitawi",
  "TWU": "Tawau",
  "TXK": "Texarkana",
  "TXN": "Tunxi",
  "TYD": "Tynda",
  "TYF": "Torsby",
  "TYL": "Talara",
  "TYM": "Staniel Cay",
  "TYN": "Taiyuan",
  "TYR": "Tyler",
  "TYS": "Knoxville",
  "TZA": "Belize City",
  "TZL": "Tuzla",
  "TZN": "South Andros",
  "TZX": "Trabzon",
  "UAH": "Ua Huka",
  "UAK": "Narsarsuaq",
  "UAP": "Ua Pou",
  "UAQ": "San Juan",
  "UAS": "Samburu",
  "UBA": "Uberaba",
  "UBB": "Mabuiag Island",
  "UBJ": "Ube Jp",
  "UBP": "Ubon Ratchath",
  "UBU": "Kalumburu",
  "UCT": "Ukhta",
  "UDI": "Uberlandia",
  "UDR": "Udaipur",
  "UEL": "Quelimane",
  "UEO": "Kume Jima",
  "UET": "Quetta",
  "UFA": "Ufa",
  "UGC": "Urgench",
  "UGI": "Uganik",
  "UHS": "Aleksandrovsk-Sakhalinkiy",
  "UIB": "Quibdo",
  "UIH": "Qui Nhon",
  "UIN": "Quincy",
  "UIO": "Quito",
  "UIT": "Jaluit",
  "UKA": "Ukunda",
  "UKB": "Osaka",
  "UKE": "Utkela",
  "UKK": "Ust Kamenogorsk",
  "UKX": "Ust-Kut",
  "ULG": "Ulgit",
  "ULO": "Ulaangom",
  "ULP": "Quilpie",
  "ULV": "Ulyanovsk",
  "ULZ": "Uliastai",
  "UMB": "Umnak Island",
  "UMD": "Uummannaq",
  "UME": "Umea",
  "UMU": "Umuarama",
  "UNA": "Una BR",
  "UNG": "Kiunga",
  "UNI": "Union Island",
  "UNK": "Unalakleet",
  "UNN": "Ranong",
  "UOL": "Buol",
  "UPG": "Ujung Pandang",
  "UPN": "Uruapan",
  "URA": "Uralsk",
  "URC": "Urumqi",
  "URE": "Kuressaare",
  "URG": "Uruguaina",
  "URJ": "Uraj",
  "URT": "Surat Thani",
  "URY": "Gurayat",
  "USH": "Ushuaia",
  "USK": "Usinsk",
  "USM": "Koh Samui",
  "USN": "Ulsan",
  "USU": "Busuanga",
  "UTH": "Udon Thani",
  "UTK": "Utirik Island",
  "UTN": "Upington",
  "UTP": "U Tapao",
  "UTS": "Ust-Tsylma",
  "UTT": "Umtata",
  "UUA": "Bugulma",
  "UUD": "Ulan Ude",
  "UUK": "Kuparuk",
  "UUS": "Yuzhno Sakhalinsk",
  "UVE": "Ouvea",
  "UVF": "St Lucia",
  "UVI": "Uniao da Vitoria",
  "UYN": "Yulin",
  "VAA": "Vaasa",
  "VAG": "Varginha",
  "VAI": "Vanimo",
  "VAK": "Chevak",
  "VAN": "Van TR",
  "VAO": "Suavanao",
  "VAQ": "Vanavara",
  "VAR": "Varna",
  "VAS": "Sivas",
  "VAV": "Vava U",
  "VAW": "Vardoe",
  "VBV": "Vanuabalavu",
  "VBY": "Visby",
  "VCA": "Can Tho",
  "VCE": "Venice",
  "VCL": "Tamky",
  "VCP": "Sao Paulo",
  "VCS": "Con Dao",
  "VCT": "Victoria",
  "VDC": "Vitoria Da Conquista",
  "VDE": "Valverde",
  "VDH": "Dong Hoi",
  "VDM": "Viedma",
  "VDS": "Vadso",
  "VDZ": "Valdez",
  "VEE": "Venetie",
  "VEL": "Vernal",
  "VEO": "Yeniseyskiy",
  "VER": "Veracruz",
  "VFA": "Victoria Falls",
  "VGA": "Vijayawada",
  "VGD": "Vologda",
  "VGO": "Vigo",
  "VGZ": "Villagarzon",
  "VHC": "Saurimo",
  "VHM": "Vilhelmina",
  "VHZ": "Vahitahi",
  "VIE": "Vienna",
  "VIG": "El Vigia",
  "VII": "Vinh City",
  "VIJ": "Virgin Gorda",
  "VIL": "Dakhla",
  "VIT": "Vitoria",
  "VIX": "Vitoria",
  "VKG": "Rach Gia",
  "VKO": "Moscow",
  "VKT": "Vorkuta",
  "VLC": "Valencia",
  "VLD": "Valdosta",
  "VLI": "Port Vila",
  "VLL": "Valladolid",
  "VLN": "Valencia",
  "VLV": "Valera",
  "VNO": "Vilnius",
  "VNS": "Varanasi",
  "VNX": "Vilanculos",
  "VNY": "Los Angeles",
  "VOG": "Volgograd",
  "VOL": "Volos",
  "VPE": "Ongiva",
  "VPN": "Vopnafjordur",
  "VPS": "Valparaiso",
  "VPY": "Chimoio",
  "VQS": "Vieques",
  "VRA": "Varadero",
  "VRB": "Vero Beach",
  "VRC": "Virac",
  "VRL": "Vila Real",
  "VRN": "Verona",
  "VRY": "Vaeroy",
  "VSA": "Villahermosa",
  "VSE": "Viseu",
  "VST": "Stockholm",
  "VSV": "Shravasti",
  "VTE": "Vientiane",
  "VTZ": "Vishakhapatanam",
  "VUP": "Valleduper",
  "VUS": "Velikij Ustyug",
  "VVC": "Villavicencio",
  "VVI": "Santa Cruz",
  "VVO": "Vladivostok",
  "VVZ": "Illizi",
  "VXC": "Lichinga",
  "VXE": "Sao Vicente",
  "VXO": "Vaxjo",
  "WAA": "Wales",
  "WAE": "Wadi Ad Dawasir",
  "WAG": "Wanganui",
  "WAW": "Warsaw",
  "WBB": "Stebbins",
  "WBM": "Wapenamanda",
  "WDH": "Windhoek",
  "WEF": "Weifang",
  "WEH": "Weihai",
  "WEI": "Weipa",
  "WGA": "Wagga Wagga",
  "WGE": "Walgett",
  "WGN": "Shaoyang",
  "WGP": "Waingapu",
  "WHA": "Wuhu",
  "WHK": "Whakatane",
  "WIC": "Wick",
  "WIL": "Nairobi",
  "WIN": "Winton",
  "WJA": "Woja",
  "WJR": "Wajir",
  "WJU": "WonJu",
  "WKA": "Wanaka",
  "WKJ": "Wakkanai",
  "WLG": "Wellington",
  "WLK": "Selawik",
  "WLS": "Wallis Island",
  "WMI": "Warsaw",
  "WMN": "Maroantsetra",
  "WMO": "White Mountain",
  "WMX": "Wamena",
  "WNA": "Napakiak",
  "WNH": "Wenshan",
  "WNN": "Wunnummin Lake",
  "WNP": "Naga",
  "WNR": "Windorah",
  "WNZ": "Wenzhou",
  "WOL": "Wollongong",
  "WPL": "Powell Lake",
  "WPR": "Porvenir",
  "WPU": "Puerto Williams",
  "WRE": "Whangarei",
  "WRG": "Wrangell",
  "WRO": "Wroclaw",
  "WRZ": "Weerawila",
  "WST": "Westerly",
  "WSZ": "Westport",
  "WTE": "Wotje",
  "WTK": "Noatak",
  "WTL": "Tuntatuliak",
  "WUA": "Wuhai",
  "WUH": "Wuhan",
  "WUN": "Wiluna",
  "WUS": "Wuyishan",
  "WUX": "Wuxi",
  "WUZ": "Wuzhou",
  "WVB": "Walvis Bay",
  "WWK": "Wewak",
  "WWP": "Whale Pass",
  "WWT": "Newtok",
  "WXN": "Wanxian",
  "WYA": "Whyalla",
  "WYS": "West Yellowstone",
  "XAP": "Chapeco",
  "XBE": "Bearskin Lake",
  "XBJ": "Birjand",
  "XCH": "Christmas Island",
  "XCR": "Chalons Sur Marne",
  "XEQ": "Tasiuasaq",
  "XFN": "Xiangfan",
  "XGR": "Kangiqsualujjuaq",
  "XIC": "Xichang",
  "XIL": "Xilinhot",
  "XIQ": "Ilimanaq",
  "XIY": "Xi An",
  "XKH": "Xieng Khouang",
  "XKS": "Kasabonika",
  "XMH": "Manihi",
  "XMN": "Xiamen",
  "XMY": "Yam Island",
  "XNA": "Fayetteville",
  "XNN": "Xining",
  "XNT": "Xingtai",
  "XPL": "Tegucigalpa",
  "XQP": "Quepos",
  "XRY": "Jerez De La Frontera",
  "XSC": "South Caicos",
  "XSP": "Singapore",
  "XTG": "Thargomindah",
  "XUZ": "Xuzhou",
  "XWA": "Williston",
  "YAA": "Anahim Lake",
  "YAB": "Arctic Bay",
  "YAC": "Cat Lake",
  "YAK": "Yakutat",
  "YAM": "Sault Ste Marie",
  "YAP": "Yap FM",
  "YAT": "Attawapiskat",
  "YAX": "Angling Lake",
  "YAY": "St Anthony",
  "YAZ": "Tofino",
  "YBB": "Pelly Bay",
  "YBC": "Baie Comeau",
  "YBE": "Uranium City",
  "YBG": "Bagotville",
  "YBK": "Baker Lake",
  "YBL": "Campbell River",
  "YBP": "Yibin",
  "YBR": "Brandon",
  "YBV": "Berens River",
  "YBX": "Blanc Sablon",
  "YCB": "Cambridge Bay",
  "YCD": "Nanaimo",
  "YCG": "Castlegar",
  "YCK": "Colville",
  "YCO": "Kugluktuk Coppermine",
  "YCS": "Chesterfield Inlet",
  "YCU": "Yun Cheng",
  "YCY": "Clyde River",
  "YDA": "Dawson City",
  "YDF": "Deer Lake",
  "YDP": "Nain",
  "YDV": "Bloodvein",
  "YEG": "Edmonton",
  "YEI": "Bursa",
  "YEK": "Arviat",
  "YER": "Fort Severn",
  "YES": "Yasouj",
  "YEV": "Inuvik",
  "YFA": "Fort Albany",
  "YFB": "Iqaluit",
  "YFC": "Fredericton",
  "YFH": "Fort Hope",
  "YFJ": "Snare Lake",
  "YFO": "Flin Flon",
  "YFS": "Fort Simpson",
  "YGG": "Ganges Harbor",
  "YGH": "Fort Good Hope",
  "YGJ": "Yonago",
  "YGL": "La Grande",
  "YGO": "Gods Lake Narrows",
  "YGP": "Gaspe",
  "YGR": "Iles De Madeleine",
  "YGT": "Igloolik",
  "YGV": "Havre St Pierre",
  "YGW": "Poste De La Baleine",
  "YGX": "Gillam",
  "YGZ": "Grise Fiord",
  "YHD": "Dryden",
  "YHI": "Holman Island",
  "YHK": "Gjoa Haven",
  "YHM": "Toronto",
  "YHO": "Hopedale",
  "YHP": "Poplar Hill",
  "YHR": "Chevery",
  "YHS": "Sechelt",
  "YHU": "Montreal",
  "YHY": "Hay River",
  "YHZ": "Halifax",
  "YIA": "Yogjakarta",
  "YIF": "Pakuashipi",
  "YIH": "Yichang",
  "YIK": "Ivujivik",
  "YIN": "Yining",
  "YIO": "Pond Inlet",
  "YIV": "Island Lake",
  "YIW": "Yiwu",
  "YKA": "Kamloops",
  "YKF": "Kitchener",
  "YKG": "Kangirsuk",
  "YKL": "Schefferville",
  "YKM": "Yakima",
  "YKQ": "Waskaganish",
  "YKS": "Yakutsk",
  "YKU": "Chisasibi",
  "YLC": "Kimmirut Lake Harbour",
  "YLE": "Wha Ti/Lac La Martre",
  "YLH": "Lansdowne",
  "YLW": "Kelowna",
  "YLX": "Yulin",
  "YMM": "Ft McMurray",
  "YMN": "Makkovik",
  "YMO": "Moosonee",
  "YMT": "Chibougamau",
  "YMX": "Montreal",
  "YNA": "Natashquan",
  "YNB": "Yanbo",
  "YNC": "Wemindji",
  "YNJ": "Yanji",
  "YNL": "Points North Landing",
  "YNO": "North Spirit Lake ON",
  "YNP": "Natuashish",
  "YNS": "Nemiscau",
  "YNT": "Yantai",
  "YNZ": "Yancheng",
  "YOC": "Old Crow",
  "YOG": "Ogoki",
  "YOH": "Oxford House",
  "YOJ": "High Level",
  "YOL": "Yola",
  "YOW": "Ottawa",
  "YPA": "Prince Albert",
  "YPH": "Inukjuak",
  "YPJ": "Aupaluk",
  "YPL": "Pickle Lake",
  "YPM": "St Pierre",
  "YPN": "Port-Menier",
  "YPO": "Peawanuck",
  "YPR": "Prince Rupert",
  "YPW": "Powell River",
  "YPX": "Puvirnituq",
  "YPY": "Fort Chipewyan",
  "YQB": "Quebec",
  "YQC": "Quaqtaq",
  "YQD": "The Pas",
  "YQG": "Windsor",
  "YQK": "Kenora",
  "YQL": "Lethbridge",
  "YQM": "Moncton",
  "YQQ": "Comox",
  "YQR": "Regina",
  "YQT": "Thunder Bay",
  "YQU": "Grande Prairie",
  "YQX": "Gander",
  "YQY": "Sydney",
  "YQZ": "Quesnel",
  "YRA": "Rae Lakes",
  "YRB": "Resolute",
  "YRG": "Rigolet",
  "YRL": "Red Lake",
  "YRS": "Red Sucker Lake",
  "YRT": "Rankin Inlet",
  "YSB": "Sudbury",
  "YSF": "Stony Rapids",
  "YSG": "Lutselke/Snowdrift",
  "YSJ": "St John",
  "YSK": "Sanikiluaq",
  "YSM": "Ft Smith",
  "YSO": "Postville",
  "YST": "St Theris Point",
  "YTE": "Cape Dorset",
  "YTH": "Thompson",
  "YTL": "Big Trout",
  "YTP": "Tofino",
  "YTQ": "Tasiujaq",
  "YTS": "Timmins",
  "YTW": "Yutian",
  "YTZ": "Toronto",
  "YUD": "Umiujaq",
  "YUL": "Montreal",
  "YUM": "Yuma",
  "YUS": "Ba Tong",
  "YUT": "Repulse Bay",
  "YUX": "Hall Beach",
  "YUY": "Rouyn Noranda",
  "YVB": "Bonaventure",
  "YVC": "La Ronge",
  "YVM": "Qikiqtarjuaq",
  "YVO": "Val D Or",
  "YVP": "Kuujjuaq",
  "YVQ": "Norman Wells",
  "YVR": "Vancouver",
  "YVZ": "Deer Lake",
  "YWB": "Kangiqsujuaq",
  "YWG": "Winnipeg",
  "YWH": "Victoria",
  "YWJ": "Deline",
  "YWK": "Wabush",
  "YWL": "Williams Lake",
  "YWP": "Webequie",
  "YWS": "Whistler",
  "YXC": "Cranbrook",
  "YXE": "Saskatoon",
  "YXH": "Medicine Hat",
  "YXJ": "Ft St John",
  "YXL": "Sioux Lookout",
  "YXN": "Whale Cove",
  "YXP": "Pangnirtung",
  "YXS": "Prince George",
  "YXT": "Terrace",
  "YXU": "London",
  "YXX": "Abbotsford",
  "YXY": "Whitehorse",
  "YYA": "Yueyang",
  "YYB": "North Bay",
  "YYC": "Calgary",
  "YYD": "Smithers",
  "YYE": "Fort Nelson",
  "YYF": "Penticton",
  "YYG": "Charlottetown",
  "YYH": "Taloyoak",
  "YYJ": "Victoria",
  "YYQ": "Churchill",
  "YYR": "Goose Bay",
  "YYT": "St Johns",
  "YYY": "Mont Joli",
  "YYZ": "Toronto",
  "YZF": "Yellowknife",
  "YZG": "Salluit",
  "YZP": "Sandspit",
  "YZS": "Coral Harbour",
  "YZT": "Port Hardy",
  "YZV": "Sept Iles",
  "YZZ": "Trail",
  "ZAD": "Zadar",
  "ZAG": "Zagreb",
  "ZAH": "Zahedan",
  "ZAJ": "Zaranj",
  "ZAL": "Valdivia",
  "ZAM": "Zamboanga",
  "ZAT": "Zhaotong",
  "ZAZ": "Zaragoza",
  "ZBF": "Bathurst",
  "ZBL": "Biloela",
  "ZBR": "Chah-Bahar",
  "ZBY": "Sayaboury",
  "ZCL": "Zacatecas",
  "ZCO": "Temuco",
  "ZEL": "Bella Bella",
  "ZEM": "East Main",
  "ZER": "Zero",
  "ZFD": "Fond Du Lac",
  "ZFL": "South Trout Lake",
  "ZFN": "Tulita/Fort Norman",
  "ZGI": "Gods River",
  "ZGS": "Gethsemanie",
  "ZHA": "Zhangjiang",
  "ZHY": "Zhongwei",
  "ZIA": "Moscow",
  "ZIH": "Zihuatanejo",
  "ZKE": "Kaschechewan",
  "ZKP": "Zyryanka",
  "ZLO": "Manzanillo",
  "ZLT": "La Tabatiere",
  "ZMT": "Masset",
  "ZNA": "Nanaimo",
  "ZNE": "Newman",
  "ZNZ": "Zanzibar",
  "ZOS": "Osorno",
  "ZPB": "Sachigo Lake",
  "ZQN": "Queenstown",
  "ZRH": "Zurich",
  "ZRI": "Serui",
  "ZRJ": "Round Lake",
  "ZSA": "San Salvador",
  "ZSJ": "Sandy Lake",
  "ZTA": "Tureira",
  "ZTB": "Tete A La Baleine",
  "ZTH": "Zakinthos",
  "ZUH": "Zhuhai",
  "ZUM": "Churchhill Falls",
  "ZVK": "Savannakhet",
  "ZWL": "Wollaston Lake",
  "ZYI": "Zunyi",
  "ZYL": "Sylhet",
};

export default cityByIata;